#!/usr/bin/env bash
# Stage the in-process Rust control core into the app's build tree
# (BLUEZ_BACKEND_PLAN.md Phase 4). Produces, from a plain checkout:
#
#   app/thirdparty/libelectriceelcore.a   aarch64 glibc staticlib (the C ABI)
#   app/thirdparty/electriceelcore.h      cbindgen header (also regenerated by
#                                          helper/build.rs on every cargo build)
#   app/bin/tesla-session                 Go BLE child, bundled in the app RPM
#
# These land inside app/ so the qmake tree (the .pro's INCLUDEPATH/LIBS plus a
# bindir INSTALLS rule) picks them up and the app RPM carries them under
# /usr/share/harbour-electric-eel/ (bin/ for the child). Nothing here is
# committed to git (see .gitignore) - they're build output of the host
# cross-compile, exactly like the pre-Phase-4 Go binaries in helper/dist/.
#
# IMPORTANT - target triple: the app links against Sailfish's glibc (Qt5), so
# the staticlib must be built for aarch64-unknown-linux-gnu, NOT the musl
# target used for the standalone electric-eel-daemon binary. Linking a musl
# .a into the glibc app would duplicate libc symbols.
set -euo pipefail

repo_root="$(cd "$(dirname "$0")/.." && pwd)"
helper_dir="$repo_root/helper"
app_dir="$repo_root/app"
target_triple="aarch64-unknown-linux-gnu"

mkdir -p "$app_dir/thirdparty" "$app_dir/bin"

if ! rustup target list --installed | grep -q "^$target_triple$"; then
    echo "Installing rust std for $target_triple (needed to cross-build the staticlib)"
    rustup target add "$target_triple"
fi

echo "Cross-compiling libelectriceelcore.a ($target_triple, glibc)"
(cd "$helper_dir" && cargo build --release --target "$target_triple" --lib --features app-entry)

install -m 0644 "$helper_dir/target/$target_triple/release/libelectriceelcore.a" \
    "$app_dir/thirdparty/libelectriceelcore.a"
# build.rs regenerates the header on every cargo build; the copy in the app
# tree must stay in lockstep (same crate build), so install the fresh one.
install -m 0644 "$helper_dir/electriceelcore.h" "$app_dir/thirdparty/electriceelcore.h"

echo "Cross-compiling tesla-session (Go, aarch64)"
(cd "$helper_dir/session" && CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -o "$app_dir/bin/tesla-session" .)

file "$app_dir/thirdparty/libelectriceelcore.a" "$app_dir/bin/tesla-session"
echo "Staged: app/thirdparty/{libelectriceelcore.a,electriceelcore.h}, app/bin/tesla-session"
