#!/usr/bin/env python3
"""Batch C: nb fi cs sk sl pl. See fill-a.py / fill_common.py."""
import os
import sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from fill_common import write_all


def T(*items):
    return list(items)


LANGS = {
"nb": T(
"Kjør",
" (valgfritt)",
"(ikke angitt)",
"%1 • %2 °C inne",
"Klima på",
"Klima av",
"%1 % batteri%2",
" • Lader",
"Dører låst",
"Dører ulåst",
"OK",
"exitkode %1",
"Kjører %1...",
"Oppmerksomhet",
"Tut",
"Blink med frontlysene",
"Vekk kjøretøyet",
"Klima",
"Slå på klima",
"Slå av klima",
"Still inn temperatur",
"Setevarme",
"Rattvarme",
"Sete & klima automatisk",
"Legg til planlagt forkondisjonering",
"Fjern planlagt forkondisjonering",
"Lading",
"Start lading",
"Stopp lading",
"Åpne ladeluke",
"Lukk ladeluke",
"Sett ladegrense",
"Sett ladestrøm",
"Planlegg lading",
"Avbryt planlagt lading",
"Legg til ladeplan",
"Fjern ladeplan",
"Lås & sikkerhet",
"Lås",
"Lås opp",
"Fjernstart (nøkkelfri kjøring)",
"Vaktmodus",
"Valetmodus på",
"Valetmodus av",
"Gjestemodus på",
"Gjestemodus av",
"Slett gjestedata",
"Autosikring (Model X)",
"Bagasjerom & vinduer",
"Åpne bakluke",
"Beveg bakluke",
"Lukk bakluke",
"Åpne frunk",
"Åpne tonneau (Cybertruck)",
"Lukk tonneau (Cybertruck)",
"Stopp tonneau (Cybertruck)",
"Lufte vinduene",
"Lukk vinduene",
"Media",
"Spill / Pause",
"Neste spor",
"Forrige spor",
"Neste favoritt",
"Forrige favoritt",
"Volum opp",
"Volum ned",
"Sett volum",
"Programvare",
"Start programvareoppdatering",
"Avbryt programvareoppdatering",
"Nøkler",
"Vis registrerte nøkler",
"Legg til nøkkel",
"Fjern nøkkel",
"Øktinfo",
"Diagnostikk",
"Ping kjøretøyet",
"Hent kjøretøystatus",
"Status for karosseristyreenhet",
"Behold tilbehørsstrøm",
"Strømsparingsmodus",
"Styringskjernen kunne ikke starte. Installer appen på nytt og dra ned for å oppdatere.",
"Styringskjernen er for gammel til å rapportere versjonen. Installer appen (%1) på nytt og dra ned for å oppdatere.",
"Versjonskonflikt: app %1, kjerne %2. Installer appen på nytt og dra ned for å oppdatere.",
"Ingen VIN konfigurert",
"Nøkkel klar",
"Ingen nøkkel - trykk for Innstillinger / Paring",
" • lader",
"• %1 °C",
"Oppdaterer...",
"Status utilgjengelig (%1). Kjøretøyet sover kanskje - prøv Vekk kjøretøyet (Oppmerksomhet) og deretter Oppdater status.",
"Dra ned for å oppdatere status",
"Oppdatert akkurat nå",
"Oppdatert for %1 min siden",
"Kategorier",
"Send destinasjon",
"Par kjøretøy",
"Innstillinger",
"Oppdater",
"Oppdater status",
"Lim inn eller skriv først en destinasjon.",
"Kontrollerer...",
"Ingenting å sende.",
"Kan ikke brukes: %1",
"Koordinater %1, %2 — navigeringen starter der.",
"Adresse ”%1” — bilen slår den opp.",
"Sending feilet: %1",
"Bilnavigasjon",
"Destinasjon",
"Lim inn adresse, koordinater eller kartlenke",
"Forhåndsvisning",
"Send til bilen",
"Merknader",
"Bruker Bluetooth, som lås/lås opp — bilen må være innen rekkevidde, intet internett trengs. Koordinater sendes nøyaktig; adresser og lenker slår bilen selv opp, så uvanlige stavemåter kan tolkes annerledes enn på telefonen. Fra Android-apper: kopier adressen eller lenken og lim inn ovenfor.",
"Nøkkel opprettet. Trykk på ”Par kjøretøy” og hold NFC-kortet mot midtkonsollen når bilskjermen ber om det.",
"Oppretting av nøkkel feilet: %1",
"Parret.",
"Paring feilet: %1",
"Paring & nøkler",
"Sett først VIN i Innstillinger. Opprett deretter en nøkkel og par den med bilen via BLE - stå ved kjøretøyet og hold NFC-kortet mot midtkonsollen for å godkjenne.",
"Telefonnøkkel starter...",
"Genererer...",
"Generer nøkkel",
"Venter på NFC-trykk...",
"Par kjøretøy",
"BLE-paring forespurt - godkjenn på berøringsskjermen / NFC-kortet nå.",
"Registrerte nøkler",
"Vis registrerte nøkler",
"Laster konfigurasjon...",
"Nøkkel finnes",
"Ingen nøkkel ennå - bruk Par kjøretøy i hovedmenyen",
"Lagret",
"Lagring feilet: %1",
"Innstillinger",
"Kjøretøyets VIN",
"17-tegns VIN",
"Bilmodell på forsiden",
"Auto velger modellen ut fra VIN",
"Nøkkelnavn",
"harbour-electric-eel",
"Tilkoblingstidsavbrudd",
" s",
"Kommandotidsavbrudd",
"Lagre",
"Paring & nøkler",
"Om",
"App: ElectricEel %1   |   kjerne: %2",
"(for gammel / ukjent)",
"Styringskjernen er for gammel til å rapportere en versjon - installer appen på nytt.",
"Versjonskonflikt: kjerne %1 vs app %2 - installer appen på nytt.",
"Auto (fra VIN)",
"Model 3",
"Model S",
"Model X",
"Model Y",
"Cybertruck",
),
"fi": T(
"Suorita",
" (valinnainen)",
"(ei asetettu)",
"%1 • %2 °C sisällä",
"Ilmastointi päällä",
"Ilmastointi pois",
"%1 % akku%2",
" • Lataa",
"Ovet lukittu",
"Ovet avattu",
"OK",
"paluukoodi %1",
"Suoritetaan %1...",
"Huomio",
"Tööttäys",
"Valojen vilkutus",
"Herätä ajoneuvo",
"Ilmastointi",
"Kytke ilmastointi",
"Sammuta ilmastointi",
"Aseta lämpötila",
"Istuimenlämmitin",
"Ohjauspyöränlämmitin",
"Istuin & ilmastointi automaattisesti",
"Lisää ajastettu esikäsittely",
"Poista ajastettu esikäsittely",
"Lataus",
"Aloita lataus",
"Lopeta lataus",
"Avaa latausluukku",
"Sulje latausluukku",
"Aseta latausraja",
"Aseta latausvirta",
"Ajasta lataus",
"Peruuta ajastettu lataus",
"Lisää latausaikataulu",
"Poista latausaikataulu",
"Lukot & turvallisuus",
"Lukitse",
"Avaa lukitus",
"Etäkäynnistys (avaimeton ajo)",
"Vartiotila",
"Valet-tila päälle",
"Valet-tila pois",
"Vierastila päälle",
"Vierastila pois",
"Tyhjennä vierastiedot",
"Automaattisuojaus (Model X)",
"Tavaratilat & ikkunat",
"Avaa takaluukku",
"Liikuta takaluukkua",
"Sulje takaluukku",
"Avaa etutavaratila",
"Avaa tonneau (Cybertruck)",
"Sulje tonneau (Cybertruck)",
"Pysäytä tonneau (Cybertruck)",
"Tuuleta ikkunoita",
"Sulje ikkunat",
"Media",
"Toista / Tauko",
"Seuraava kappale",
"Edellinen kappale",
"Seuraava suosikki",
"Edellinen suosikki",
"Ääni kovemmalle",
"Ääni hiljaisemmalle",
"Aseta äänenvoimakkuus",
"Ohjelmisto",
"Aloita ohjelmistopäivitys",
"Peruuta ohjelmistopäivitys",
"Avaimet",
"Listaa rekisteröidyt avaimet",
"Lisää avain",
"Poista avain",
"Istuntotiedot",
"Diagnostiikka",
"Pingaa ajoneuvoa",
"Hae ajoneuvon tila",
"Korinhallintayksikön tila",
"Pidä lisälaitevirta",
"Vähävirtatila",
"Ohjausydin ei käynnistynyt. Asenna sovellus uudelleen ja vedä alas päivittääksesi.",
"Ohjausydin on liian vanha ilmoittamaan versionsa. Asenna sovellus (%1) uudelleen ja vedä alas päivittääksesi.",
"Versioristiriita: sovellus %1, ydin %2. Asenna sovellus uudelleen ja vedä alas päivittääksesi.",
"VIN-numeroa ei asetettu",
"Avain valmis",
"Ei avainta - napauta Asetukset / Paritus",
" • lataa",
"• %1 °C",
"Päivitetään...",
"Tila ei saatavilla (%1). Ajoneuvo saattaa nukkua - kokeile Herätä ajoneuvo (Huomio) ja Päivitä tila.",
"Vedä alas päivittääksesi tilan",
"Päivitetty juuri",
"Päivitetty %1 min sitten",
"Luokat",
"Lähetä kohde",
"Parita ajoneuvo",
"Asetukset",
"Päivitä",
"Päivitä tila",
"Liitä tai kirjoita ensin kohde.",
"Tarkistetaan...",
"Ei lähetettävää.",
"Ei käytettävissä: %1",
"Koordinaatit %1, %2 — navigointi alkaa sieltä.",
"Osoite ”%1” — auto hakee sen.",
"Lähetys epäonnistui: %1",
"Auton navigointi",
"Kohde",
"Liitä osoite, koordinaatit tai karttalinkki",
"Esikatselu",
"Lähetä autoon",
"Huomautukset",
"Käyttää Bluetoothia kuten lukitus/avaus — auton on oltava kantaman sisällä, internetiä ei tarvita. Koordinaatit lähetetään tarkasti; osoitteet ja linkit auto hakee itse, joten epätavalliset kirjoitusasut voivat tulkita eri tavoin kuin puhelimessa. Android-sovelluksista: kopioi osoite tai linkki ja liitä yllä.",
"Avain luotu. Napauta ”Parita ajoneuvo” ja paina NFC-korttia keskikonsoliin, kun auton näyttö pyytää.",
"Avaimen luonti epäonnistui: %1",
"Paritettu.",
"Paritus epäonnistui: %1",
"Paritus & avaimet",
"Aseta ensin VIN Asetuksissa. Luo sitten avain ja parita se autoon BLE:llä - seiso ajoneuvon vieressä ja paina NFC-korttia keskikonsoliin hyväksyäksesi.",
"Puhelinavain käynnistyy...",
"Luodaan...",
"Luo avain",
"Odotetaan NFC-kosketusta...",
"Parita ajoneuvo",
"BLE-paritus pyydetty - hyväksy kosketusnäytöllä / NFC-kortilla nyt.",
"Rekisteröidyt avaimet",
"Listaa rekisteröidyt avaimet",
"Ladataan asetuksia...",
"Avain olemassa",
"Ei avainta vielä - käytä Parita ajoneuvo päävalikossa",
"Tallennettu",
"Tallennus epäonnistui: %1",
"Asetukset",
"Ajoneuvon VIN",
"17-merkkinen VIN",
"Automalli etusivulla",
"Auto valitsee mallin VIN-numerosta",
"Avaimen nimi",
"harbour-electric-eel",
"Yhteyden aikakatkaisu",
" s",
"Komennon aikakatkaisu",
"Tallenna",
"Paritus & avaimet",
"Tietoa",
"Sovellus: ElectricEel %1   |   ydin: %2",
"(liian vanha / tuntematon)",
"Ohjausydin on liian vanha ilmoittamaan versiota - asenna sovellus uudelleen.",
"Versioristiriita: ydin %1 vs sovellus %2 - asenna sovellus uudelleen.",
"Auto (VIN-numerosta)",
"Model 3",
"Model S",
"Model X",
"Model Y",
"Cybertruck",
),
"cs": T(
"Spustit",
" (volitelné)",
"(nenastaveno)",
"%1 • %2 °C uvnitř",
"Klimatizace zapnuta",
"Klimatizace vypnuta",
"%1 % baterie%2",
" • Nabíjí se",
"Dveře zamčeny",
"Dveře odemčeny",
"OK",
"návratový kód %1",
"Spouštím %1...",
"Pozornost",
"Zatroubení",
"Bliknutí světly",
"Probudit vozidlo",
"Klimatizace",
"Zapnout klimatizaci",
"Vypnout klimatizaci",
"Nastavit teplotu",
"Vyhřívání sedadel",
"Vyhřívání volantu",
"Sedadla a klima automaticky",
"Přidat plánované předehřátí",
"Odebrat plánované předehřátí",
"Nabíjení",
"Zahájit nabíjení",
"Ukončit nabíjení",
"Otevřít nabíjecí port",
"Zavřít nabíjecí port",
"Nastavit limit nabíjení",
"Nastavit nabíjecí proud",
"Naplánovat nabíjení",
"Zrušit plánované nabíjení",
"Přidat plán nabíjení",
"Odebrat plán nabíjení",
"Zámky a zabezpečení",
"Zamknout",
"Odemknout",
"Vzdálený start (jízda bez klíče)",
"Režim Sentry",
"Zapnout režim Valet",
"Vypnout režim Valet",
"Zapnout režim hosta",
"Vypnout režim hosta",
"Smazat data hosta",
"Autozabezpečení (Model X)",
"Kufry a okna",
"Otevřít zadní kufr",
"Pohybovat zadním kufrem",
"Zavřít zadní kufr",
"Otevřít přední kufr",
"Otevřít tonneau (Cybertruck)",
"Zavřít tonneau (Cybertruck)",
"Zastavit tonneau (Cybertruck)",
"Vyvětrat okna",
"Zavřít okna",
"Média",
"Přehrát / Pauza",
"Další skladba",
"Předchozí skladba",
"Další oblíbená",
"Předchozí oblíbená",
"Zesílit",
"Zeslabit",
"Nastavit hlasitost",
"Software",
"Zahájit aktualizaci softwaru",
"Zrušit aktualizaci softwaru",
"Klíče",
"Vypsat registrované klíče",
"Přidat klíč",
"Odebrat klíč",
"Info o relaci",
"Diagnostika",
"Ping vozidla",
"Načíst stav vozidla",
"Stav řídicí jednotky karoserie",
"Ponechat napájení příslušenství",
"Úsporný režim",
"Řídicí jádro se nespustilo. Přeinstaluj aplikaci a tažením dolů obnov.",
"Řídicí jádro je příliš staré a nehlásí verzi. Přeinstaluj aplikaci (%1) a tažením dolů obnov.",
"Nesoulad verzí: aplikace %1, jádro %2. Přeinstaluj aplikaci a tažením dolů obnov.",
"Nenakonfigurováno VIN",
"Klíč připraven",
"Žádný klíč – klepni pro Nastavení / Párování",
" • nabíjí se",
"• %1 °C",
"Aktualizuje se...",
"Stav nedostupný (%1). Vozidlo možná spí – zkus Probudit vozidlo (Pozornost) a pak Obnovit stav.",
"Tažením dolů obnovíš stav",
"Aktualizováno právě teď",
"Aktualizováno před %1 min",
"Kategorie",
"Odeslat cíl",
"Spárovat vozidlo",
"Nastavení",
"Obnovit",
"Obnovit stav",
"Nejprve vlož nebo napiš cíl.",
"Kontroluje se...",
"Nic k odeslání.",
"Nelze použít: %1",
"Souřadnice %1, %2 — navigace tam začne.",
"Adresa „%1“ — vůz ji vyhledá.",
"Odeslání selhalo: %1",
"Navigace vozu",
"Cíl",
"Vlož adresu, souřadnice nebo odkaz na mapu",
"Náhled",
"Odeslat do vozu",
"Poznámky",
"Používá Bluetooth jako zamykání/odemykání — vůz musí být v dosahu, internet není potřeba. Souřadnice se posílají přesně; adresy a odkazy si vůz vyhledá sám, takže neobvyklý pravopis se může vyhodnotit jinak než v telefonu. Z aplikací pro Android: zkopíruj adresu nebo odkaz a vlož výše.",
"Klíč vygenerován. Klepni na „Spárovat vozidlo“ a přilož NFC kartu na středovou konzoli, až si to vyžádá displej vozu.",
"Generování klíče selhalo: %1",
"Spárováno.",
"Párování selhalo: %1",
"Párování a klíče",
"Nejprve nastav VIN v Nastavení. Pak vygeneruj klíč a spáruj ho s vozem přes BLE – stůj vedle vozidla a pro schválení přilož NFC kartu na středovou konzoli.",
"Telefonní klíč se spouští...",
"Generuje se...",
"Vygenerovat klíč",
"Čeká se na přiložení NFC...",
"Spárovat vozidlo",
"Párování přes BLE vyžádáno – schval na dotykové obrazovce / NFC kartě.",
"Registrované klíče",
"Vypsat registrované klíče",
"Načítá se konfigurace...",
"Klíč existuje",
"Zatím žádný klíč – použij Spárovat vozidlo v hlavní nabídce",
"Uloženo",
"Uložení selhalo: %1",
"Nastavení",
"VIN vozidla",
"17znakové VIN",
"Model auta na úvodní stránce",
"Auto vybere model podle VIN",
"Název klíče",
"harbour-electric-eel",
"Timeout připojení",
" s",
"Timeout příkazu",
"Uložit",
"Párování a klíče",
"O aplikaci",
"Aplikace: ElectricEel %1   |   jádro: %2",
"(příliš staré / neznámé)",
"Řídicí jádro je příliš staré a nehlásí verzi – přeinstaluj aplikaci.",
"Nesoulad verzí: jádro %1 vs aplikace %2 – přeinstaluj aplikaci.",
"Auto (podle VIN)",
"Model 3",
"Model S",
"Model X",
"Model Y",
"Cybertruck",
),
"sk": T(
"Spustiť",
" (voliteľné)",
"(nenastavené)",
"%1 • %2 °C vnútri",
"Klimatizácia zapnutá",
"Klimatizácia vypnutá",
"%1 % batérie%2",
" • Nabíja sa",
"Dvere zamknuté",
"Dvere odomknuté",
"OK",
"návratový kód %1",
"Spúšťam %1...",
"Pozornosť",
"Zatrúbenie",
"Bliknutie svetlami",
"Prebudiť vozidlo",
"Klimatizácia",
"Zapnúť klimatizáciu",
"Vypnúť klimatizáciu",
"Nastaviť teplotu",
"Vyhrievanie sedadiel",
"Vyhrievanie volantu",
"Sedadlá a klíma automaticky",
"Pridať plánované predhriatie",
"Odobrať plánované predhriatie",
"Nabíjanie",
"Začať nabíjanie",
"Ukončiť nabíjanie",
"Otvoriť nabíjací port",
"Zavrieť nabíjací port",
"Nastaviť limit nabíjania",
"Nastaviť nabíjací prúd",
"Naplánovať nabíjanie",
"Zrušiť plánované nabíjanie",
"Pridať plán nabíjania",
"Odobrať plán nabíjania",
"Zámky a zabezpečenie",
"Zamknúť",
"Odomknúť",
"Vzdialený štart (jazda bez kľúča)",
"Režim Sentry",
"Zapnúť režim Valet",
"Vypnúť režim Valet",
"Zapnúť režim hosťa",
"Vypnúť režim hosťa",
"Vymazať údaje hosťa",
"Autozabezpečenie (Model X)",
"Kufre a okná",
"Otvoriť zadný kufor",
"Pohybovať zadným kufrom",
"Zavrieť zadný kufor",
"Otvoriť predný kufor",
"Otvoriť tonneau (Cybertruck)",
"Zavrieť tonneau (Cybertruck)",
"Zastaviť tonneau (Cybertruck)",
"Vyvtrať okná",
"Zavrieť okná",
"Médiá",
"Prehrať / Pauza",
"Ďalšia skladba",
"Predchádzajúca skladba",
"Ďalšia obľúbená",
"Predchádzajúca obľúbená",
"Zosilniť",
"Zoslabiť",
"Nastaviť hlasitosť",
"Softvér",
"Začať aktualizáciu softvéru",
"Zrušiť aktualizáciu softvéru",
"Kľúče",
"Vypísať registrované kľúče",
"Pridať kľúč",
"Odobrať kľúč",
"Info o relácii",
"Diagnostika",
"Ping vozidla",
"Načítať stav vozidla",
"Stav riadiacej jednotky karosérie",
"Ponechať napájanie príslušenstva",
"Úsporný režim",
"Riadiace jadro sa nespustilo. Preinštaluj aplikáciu a potiahnutím nadol obnov.",
"Riadiace jadro je príliš staré a nehlási verziu. Preinštaluj aplikáciu (%1) a potiahnutím nadol obnov.",
"Nesúlad verzií: aplikácia %1, jadro %2. Preinštaluj aplikáciu a potiahnutím nadol obnov.",
"Nenakonfigurované VIN",
"Kľúč pripravený",
"Žiadny kľúč – klepni pre Nastavenia / Párovanie",
" • nabíja sa",
"• %1 °C",
"Aktualizuje sa...",
"Stav nedostupný (%1). Vozidlo možno spí – skús Prebudiť vozidlo (Pozornosť) a potom Obnoviť stav.",
"Potiahnutím nadol obnovíš stav",
"Aktualizované práve teraz",
"Aktualizované pred %1 min",
"Kategórie",
"Odoslať cieľ",
"Spárovať vozidlo",
"Nastavenia",
"Obnoviť",
"Obnoviť stav",
"Najprv vlož alebo napíš cieľ.",
"Kontroluje sa...",
"Nič na odoslanie.",
"Nedá sa použiť: %1",
"Súradnice %1, %2 — navigácia tam začne.",
"Adresa „%1“ — vozidlo ju vyhľadá.",
"Odoslanie zlyhalo: %1",
"Navigácia vozidla",
"Cieľ",
"Vlož adresu, súradnice alebo odkaz na mapu",
"Náhľad",
"Odoslať do vozidla",
"Poznámky",
"Používa Bluetooth ako zamykanie/odomykanie — vozidlo musí byť v dosahu, internet nie je potrebný. Súradnice sa posielajú presne; adresy a odkazy si vozidlo vyhľadá samo, takže nezvyčajný pravopis sa môže vyhodnotiť inak než v telefóne. Z aplikácií pre Android: skopíruj adresu alebo odkaz a vlož vyššie.",
"Kľúč vygenerovaný. Klepni na „Spárovať vozidlo“ a prilož NFC kartu na stredovú konzolu, až si to vyžiada displej vozidla.",
"Generovanie kľúča zlyhalo: %1",
"Spárované.",
"Párovanie zlyhalo: %1",
"Párovanie a kľúče",
"Najprv nastav VIN v Nastaveniach. Potom vygeneruj kľúč a spáruj ho s vozidlom cez BLE – stoj vedľa vozidla a na schválenie prilož NFC kartu na stredovú konzolu.",
"Telefónny kľúč sa spúšťa...",
"Generuje sa...",
"Vygenerovať kľúč",
"Čaká sa na priloženie NFC...",
"Spárovať vozidlo",
"Párovanie cez BLE vyžiadané – schváľ na dotykovej obrazovke / NFC karte.",
"Registrované kľúče",
"Vypísať registrované kľúče",
"Načítava sa konfigurácia...",
"Kľúč existuje",
"Zatiaľ žiadny kľúč – použi Spárovať vozidlo v hlavnej ponuke",
"Uložené",
"Uloženie zlyhalo: %1",
"Nastavenia",
"VIN vozidla",
"17-znakové VIN",
"Model auta na úvodnej stránke",
"Auto vyberie model podľa VIN",
"Názov kľúča",
"harbour-electric-eel",
"Timeout pripojenia",
" s",
"Timeout príkazu",
"Uložiť",
"Párovanie a kľúče",
"O aplikácii",
"Aplikácia: ElectricEel %1   |   jadro: %2",
"(príliš staré / neznáme)",
"Riadiace jadro je príliš staré a nehlási verziu – preinštaluj aplikáciu.",
"Nesúlad verzií: jadro %1 vs aplikácia %2 – preinštaluj aplikáciu.",
"Auto (podľa VIN)",
"Model 3",
"Model S",
"Model X",
"Model Y",
"Cybertruck",
),
"sl": T(
"Zaženi",
" (neobvezno)",
"(ni nastavljeno)",
"%1 • %2 °C znotraj",
"Klimatska naprava vklopljena",
"Klimatska naprava izklopljena",
"%1 % baterije%2",
" • Polni se",
"Vrata zaklenjena",
"Vrata odklenjena",
"OK",
"koda izhoda %1",
"Zaganjam %1...",
"Pozornost",
"Hupa",
"Utripanje z žarometi",
"Zbudi vozilo",
"Klimatska naprava",
"Vklopi klimatsko napravo",
"Izklopi klimatsko napravo",
"Nastavi temperaturo",
"Gretje sedežev",
"Gretje volana",
"Sedeži in klima samodejno",
"Dodaj načrtovano predogrevanje",
"Odstrani načrtovano predogrevanje",
"Polnjenje",
"Začni polnjenje",
"Ustavi polnjenje",
"Odpri polnilna vrata",
"Zapri polnilna vrata",
"Nastavi omejitev polnjenja",
"Nastavi polnilni tok",
"Načrtuj polnjenje",
"Prekliči načrtovano polnjenje",
"Dodaj načrt polnjenja",
"Odstrani načrt polnjenja",
"Ključavnice in varnost",
"Zakleni",
"Odkleni",
"Oddaljeni zagon (vožnja brez ključa)",
"Način Sentry",
"Vklopi način Valet",
"Izklopi način Valet",
"Vklopi način za goste",
"Izklopi način za goste",
"Izbriši podatke gostov",
"Samodejna zaščita (Model X)",
"Prtljažniki in okna",
"Odpri zadnji prtljažnik",
"Premakni zadnji prtljažnik",
"Zapri zadnji prtljažnik",
"Odpri sprednji prtljažnik",
"Odpri tonneau (Cybertruck)",
"Zapri tonneau (Cybertruck)",
"Ustavi tonneau (Cybertruck)",
"Prezrači okna",
"Zapri okna",
"Mediji",
"Predvajaj / Premor",
"Naslednja skladba",
"Prejšnja skladba",
"Naslednji priljubljen",
"Prejšnji priljubljen",
"Glasneje",
"Tišje",
"Nastavi glasnost",
"Programska oprema",
"Začni posodobitev programske opreme",
"Prekliči posodobitev programske opreme",
"Ključi",
"Izpiši registrirane ključe",
"Dodaj ključ",
"Odstrani ključ",
"Podatki o seji",
"Diagnostika",
"Ping vozila",
"Preberi stanje vozila",
"Stanje krmilne enote karoserije",
"Ohrani napajanje dodatne opreme",
"Varčni način",
"Krmilno jedro se ni zagnalo. Znova namesti aplikacijo in povleci navzdol za osvežitev.",
"Krmilno jedro je prestaro in ne sporoča različice. Znova namesti aplikacijo (%1) in povleci navzdol za osvežitev.",
"Neskladje različic: aplikacija %1, jedro %2. Znova namesti aplikacijo in povleci navzdol za osvežitev.",
"VIN ni nastavljen",
"Ključ pripravljen",
"Ni ključa – tapni za Nastavitve / Seznanjanje",
" • se polni",
"• %1 °C",
"Posodabljanje...",
"Stanje ni na voljo (%1). Vozilo morda spi – poskusi Zbudi vozilo (Pozornost) in nato Osveži stanje.",
"Povleci navzdol za osvežitev stanja",
"Posodobljeno pravkar",
"Posodobljeno pred %1 min",
"Kategorije",
"Pošlji cilj",
"Seznani vozilo",
"Nastavitve",
"Osveži",
"Osveži stanje",
"Najprej prilepi ali vpiši cilj.",
"Preverjanje...",
"Ni nič za pošiljanje.",
"Ni uporabno: %1",
"Koordinate %1, %2 — navigacija se bo začela tam.",
"Naslov „%1“ — vozilo ga bo poiskalo.",
"Pošiljanje ni uspelo: %1",
"Navigacija vozila",
"Cilj",
"Prilepi naslov, koordinate ali povezavo zemljevida",
"Predogled",
"Pošlji v vozilo",
"Opombe",
"Uporablja Bluetooth kot zaklepanje/odklepanje — vozilo mora biti v dosegu, internet ni potreben. Koordinate se pošljejo natančno; naslove in povezave vozilo poišče samo, zato se lahko nenavadno črkovanje razreši drugače kot v telefonu. Iz aplikacij Android: kopiraj naslov ali povezavo in prilepi zgoraj.",
"Ključ ustvarjen. Tapni »Seznani vozilo« in prisloni kartico NFC na sredinsko konzolo, ko to zahteva zaslon vozila.",
"Ustvarjanje ključa ni uspelo: %1",
"Seznanjeno.",
"Seznanjanje ni uspelo: %1",
"Seznanjanje in ključi",
"Najprej nastavi VIN v Nastavitvah. Nato ustvari ključ in ga seznani z vozilom prek BLE – stoj ob vozilu in za potrditev prisloni kartico NFC na sredinsko konzolo.",
"Telefonski ključ se zaganja...",
"Ustvarjanje...",
"Ustvari ključ",
"Čakanje na dotik NFC...",
"Seznani vozilo",
"Seznanjanje BLE zahtevano – potrdi na zaslonu na dotik / kartici NFC.",
"Registrirani ključi",
"Izpiši registrirane ključe",
"Nalaganje nastavitev...",
"Ključ obstaja",
"Zaenkrat ni ključa – uporabi Seznani vozilo v glavnem meniju",
"Shranjeno",
"Shranjevanje ni uspelo: %1",
"Nastavitve",
"VIN vozila",
"17-mestni VIN",
"Model avtomobila na naslovnici",
"Samodejno izbere model iz VIN",
"Ime ključa",
"harbour-electric-eel",
"Časovna omejitev povezave",
" s",
"Časovna omejitev ukaza",
"Shrani",
"Seznanjanje in ključi",
"O programu",
"Program: ElectricEel %1   |   jedro: %2",
"(prestaro / neznano)",
"Krmilno jedro je prestaro in ne sporoča različice – znova namesti aplikacijo.",
"Neskladje različic: jedro %1 proti aplikaciji %2 – znova namesti aplikacijo.",
"Samodejno (iz VIN)",
"Model 3",
"Model S",
"Model X",
"Model Y",
"Cybertruck",
),
"pl": T(
"Uruchom",
" (opcjonalnie)",
"(nie ustawiono)",
"%1 • %2 °C wewnątrz",
"Klimatyzacja włączona",
"Klimatyzacja wyłączona",
"%1% baterii%2",
" • Ładuje się",
"Drzwi zablokowane",
"Drzwi odblokowane",
"OK",
"kod wyjścia %1",
"Uruchamiam %1...",
"Uwaga",
"Klakson",
"Mruganie światłami",
"Obudź pojazd",
"Klimatyzacja",
"Włącz klimatyzację",
"Wyłącz klimatyzację",
"Ustaw temperaturę",
"Ogrzewanie siedzeń",
"Ogrzewanie kierownicy",
"Fotele i klimatyzacja automatycznie",
"Dodaj planowane przygotowanie",
"Usuń planowane przygotowanie",
"Ładowanie",
"Rozpocznij ładowanie",
"Zatrzymaj ładowanie",
"Otwórz port ładowania",
"Zamknij port ładowania",
"Ustaw limit ładowania",
"Ustaw prąd ładowania",
"Zaplanuj ładowanie",
"Anuluj zaplanowane ładowanie",
"Dodaj harmonogram ładowania",
"Usuń harmonogram ładowania",
"Zamki i bezpieczeństwo",
"Zablokuj",
"Odblokuj",
"Zdalny start (jazda bez kluczyka)",
"Tryb Sentry",
"Włącz tryb Valet",
"Wyłącz tryb Valet",
"Włącz tryb gościa",
"Wyłącz tryb gościa",
"Wyczyść dane gościa",
"Autozabezpieczenie (Model X)",
"Bagażniki i szyby",
"Otwórz tylny bagażnik",
"Porusz tylnym bagażnikiem",
"Zamknij tylny bagażnik",
"Otwórz przedni bagażnik",
"Otwórz tonneau (Cybertruck)",
"Zamknij tonneau (Cybertruck)",
"Zatrzymaj tonneau (Cybertruck)",
"Uchyl szyby",
"Zamknij szyby",
"Multimedia",
"Odtwórz / Pauza",
"Następny utwór",
"Poprzedni utwór",
"Następny ulubiony",
"Poprzedni ulubiony",
"Głośniej",
"Ciszej",
"Ustaw głośność",
"Oprogramowanie",
"Rozpocznij aktualizację oprogramowania",
"Anuluj aktualizację oprogramowania",
"Klucze",
"Wypisz zarejestrowane klucze",
"Dodaj klucz",
"Usuń klucz",
"Info o sesji",
"Diagnostyka",
"Ping pojazdu",
"Pobierz stan pojazdu",
"Stan sterownika nadwozia",
"Utrzymaj zasilanie akcesoriów",
"Tryb niskiego zużycia",
"Rdzeń sterujący nie uruchomił się. Zainstaluj aplikację ponownie i przeciągnij w dół, aby odświeżyć.",
"Rdzeń sterujący jest za stary, aby zgłosić wersję. Zainstaluj aplikację (%1) ponownie i przeciągnij w dół, aby odświeżyć.",
"Niezgodność wersji: aplikacja %1, rdzeń %2. Zainstaluj aplikację ponownie i przeciągnij w dół, aby odświeżyć.",
"Nie skonfigurowano VIN",
"Klucz gotowy",
"Brak klucza – dotknij, aby przejść do Ustawień / Parowania",
" • ładuje się",
"• %1 °C",
"Aktualizowanie...",
"Stan niedostępny (%1). Pojazd może spać – spróbuj Obudź pojazd (Uwaga), a potem Odśwież stan.",
"Przeciągnij w dół, aby odświeżyć stan",
"Zaktualizowano przed chwilą",
"Zaktualizowano %1 min temu",
"Kategorie",
"Wyślij cel",
"Sparuj pojazd",
"Ustawienia",
"Odśwież",
"Odśwież stan",
"Najpierw wklej lub wpisz cel.",
"Sprawdzanie...",
"Nic do wysłania.",
"Nie można użyć: %1",
"Współrzędne %1, %2 — nawigacja rozpocznie się tam.",
"Adres „%1” — pojazd go wyszuka.",
"Wysyłanie nie powiodło się: %1",
"Nawigacja pojazdu",
"Cel",
"Wklej adres, współrzędne lub link do mapy",
"Podgląd",
"Wyślij do pojazdu",
"Uwagi",
"Używa Bluetooth jak blokowanie/odblokowywanie — pojazd musi być w zasięgu, internet nie jest potrzebny. Współrzędne są wysyłane dokładnie; adresy i linki pojazd wyszukuje sam, więc nietypowa pisownia może zostać rozpoznana inaczej niż w telefonie. Z aplikacji Android: skopiuj adres lub link i wklej powyżej.",
"Klucz wygenerowany. Dotknij „Sparuj pojazd” i przyłóż kartę NFC do konsoli środkowej, gdy poprosi o to ekran pojazdu.",
"Generowanie klucza nie powiodło się: %1",
"Sparowano.",
"Parowanie nie powiodło się: %1",
"Parowanie i klucze",
"Najpierw ustaw VIN w Ustawieniach. Potem wygeneruj klucz i sparuj go z pojazdem przez BLE – stań obok pojazdu i przyłóż kartę NFC do konsoli środkowej, aby zatwierdzić.",
"Klucz telefonu uruchamia się...",
"Generowanie...",
"Generuj klucz",
"Oczekiwanie na dotknięcie NFC...",
"Sparuj pojazd",
"Żądano parowania BLE – zatwierdź na ekranie dotykowym / karcie NFC.",
"Zarejestrowane klucze",
"Wypisz zarejestrowane klucze",
"Wczytywanie konfiguracji...",
"Klucz istnieje",
"Na razie brak klucza – użyj Sparuj pojazd w menu głównym",
"Zapisano",
"Zapis nie powiódł się: %1",
"Ustawienia",
"VIN pojazdu",
"17-znakowy VIN",
"Model auta na stronie głównej",
"Auto wybiera model na podstawie VIN",
"Nazwa klucza",
"harbour-electric-eel",
"Limit czasu połączenia",
" s",
"Limit czasu polecenia",
"Zapisz",
"Parowanie i klucze",
"O programie",
"Aplikacja: ElectricEel %1   |   rdzeń: %2",
"(za stary / nieznany)",
"Rdzeń sterujący jest za stary, aby zgłosić wersję – zainstaluj aplikację ponownie.",
"Niezgodność wersji: rdzeń %1 vs aplikacja %2 – zainstaluj aplikację ponownie.",
"Auto (z VIN)",
"Model 3",
"Model S",
"Model X",
"Model Y",
"Cybertruck",
),
}
if __name__ == "__main__":
    write_all(LANGS)
