#!/usr/bin/env python3
"""Batch A: de fr es pt pt_BR nl. Run after tools/fill-it.py pattern.

Positional lists matching the lupdate template order (156). The writer
validates length and %N placeholder preservation, then writes finished
_<lang>.ts files. Run tools/build-qm.sh afterwards to merge+compile.
"""
import os
import sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from fill_common import write_all


def T(*items):
    return list(items)


LANGS = {
"de": T(
"Ausführen",
" (optional)",
"(nicht festgelegt)",
"%1 • %2°C innen",
"Klima ein",
"Klima aus",
"%1% Akku%2",
" • Wird geladen",
"Türen verriegelt",
"Türen entriegelt",
"OK",
"Exit-Code %1",
"%1 wird ausgeführt...",
"Aufmerksamkeit",
"Hupe",
"Lichthupe",
"Fahrzeug aufwecken",
"Klima",
"Klima ein",
"Klima aus",
"Temperatur einstellen",
"Sitzheizung",
"Lenkradheizung",
"Sitz & Klima automatisch",
"Vorklimatisierung planen",
"Vorklimatisierung entfernen",
"Laden",
"Laden starten",
"Laden stoppen",
"Ladeanschluss öffnen",
"Ladeanschluss schließen",
"Ladelimit festlegen",
"Ladestrom festlegen",
"Laden planen",
"Geplantes Laden abbrechen",
"Ladeplan hinzufügen",
"Ladeplan entfernen",
"Verriegelung & Sicherheit",
"Verriegeln",
"Entriegeln",
"Fernstart (schlüsselloses Fahren)",
"Wächtermodus",
"Valet-Modus ein",
"Valet-Modus aus",
"Gastmodus ein",
"Gastmodus aus",
"Gastdaten löschen",
"Auto-Secure (Model X)",
"Kofferräume & Fenster",
"Heckklappe öffnen",
"Heckklappe bewegen",
"Heckklappe schließen",
"Fronthaube öffnen",
"Tonneau öffnen (Cybertruck)",
"Tonneau schließen (Cybertruck)",
"Tonneau stoppen (Cybertruck)",
"Fenster lüften",
"Fenster schließen",
"Medien",
"Abspielen / Pause",
"Nächster Titel",
"Vorheriger Titel",
"Nächster Favorit",
"Vorheriger Favorit",
"Lauter",
"Leiser",
"Lautstärke einstellen",
"Software",
"Software-Update starten",
"Software-Update abbrechen",
"Schlüssel",
"Registrierte Schlüssel auflisten",
"Schlüssel hinzufügen",
"Schlüssel entfernen",
"Sitzungsinfo",
"Diagnose",
"Fahrzeug anpingen",
"Fahrzeugstatus abrufen",
"Karosseriesteuergerät-Status",
"Zubehörstrom beibehalten",
"Energiesparmodus",
"Der Steuerungskern konnte nicht starten. Installiere die App neu und ziehe dann zum Aktualisieren nach unten.",
"Der Steuerungskern ist zu alt, um seine Version zu melden. Installiere die App (%1) neu und ziehe dann zum Aktualisieren nach unten.",
"Versionskonflikt: App %1, Kern %2. Installiere die App neu und ziehe dann zum Aktualisieren nach unten.",
"Keine VIN konfiguriert",
"Schlüssel bereit",
"Kein Schlüssel – tippe für Einstellungen / Koppeln",
" • wird geladen",
"• %1°C",
"Wird aktualisiert...",
"Status nicht verfügbar (%1). Das Fahrzeug schläft möglicherweise – versuche Fahrzeug aufwecken (Aufmerksamkeit), dann Status aktualisieren.",
"Zum Aktualisieren des Status nach unten ziehen",
"Gerade aktualisiert",
"Vor %1 Min. aktualisiert",
"Kategorien",
"Ziel senden",
"Fahrzeug koppeln",
"Einstellungen",
"Aktualisieren",
"Status aktualisieren",
"Füge zuerst ein Ziel ein oder gib eines ein.",
"Wird geprüft...",
"Nichts zu senden.",
"Nicht verwendbar: %1",
"Koordinaten %1, %2 – die Navigation startet dort.",
"Adresse „%1“ – wird vom Fahrzeug gesucht.",
"Senden fehlgeschlagen: %1",
"Fahrzeugnavigation",
"Ziel",
"Adresse, Koordinaten oder Kartenlink einfügen",
"Vorschau",
"Ans Fahrzeug senden",
"Hinweise",
"Nutzt Bluetooth wie Verriegeln/Entriegeln – das Fahrzeug muss in Reichweite sein, kein Internet nötig. Koordinaten werden exakt gesendet; Adressen und Links sucht das Fahrzeug selbst, ungewöhnliche Schreibweisen können daher anders aufgelöst werden als auf dem Telefon. Aus Android-Apps: Adresse oder Link kopieren und oben einfügen.",
"Schlüssel erzeugt. Tippe auf „Fahrzeug koppeln“ und halte dann die NFC-Karte an die Mittelkonsole, wenn das Fahrzeugdisplay dazu auffordert.",
"Schlüsselerzeugung fehlgeschlagen: %1",
"Gekoppelt.",
"Koppeln fehlgeschlagen: %1",
"Koppeln & Schlüssel",
"Trage zuerst die VIN in den Einstellungen ein. Erzeuge dann einen Schlüssel und kopple ihn per BLE mit dem Fahrzeug – du musst neben dem Fahrzeug stehen und die NFC-Karte zur Bestätigung an die Mittelkonsole halten.",
"Telefonschlüssel startet...",
"Wird erzeugt...",
"Schlüssel erzeugen",
"Warte auf NFC-Tap...",
"Fahrzeug koppeln",
"Kopplung per BLE wird angefragt – jetzt am Fahrzeug-Touchscreen / per NFC-Karte bestätigen.",
"Registrierte Schlüssel",
"Registrierte Schlüssel auflisten",
"Konfiguration wird geladen...",
"Schlüssel vorhanden",
"Noch kein Schlüssel – nutze Fahrzeug koppeln im Hauptmenü",
"Gespeichert",
"Speichern fehlgeschlagen: %1",
"Einstellungen",
"Fahrzeug-VIN",
"17-stellige VIN",
"Fahrzeugmodell auf der Startseite",
"Auto wählt das Modell anhand der VIN",
"Schlüsselname",
"harbour-electric-eel",
"Verbindungs-Timeout",
" s",
"Befehls-Timeout",
"Speichern",
"Koppeln & Schlüssel",
"Über",
"App: ElectricEel %1   |   core: %2",
"(zu alt / unbekannt)",
"Der Steuerungskern ist zu alt, um eine Version zu melden – installiere die App neu.",
"Versionskonflikt: Kern %1 vs. App %2 – installiere die App neu.",
"Auto (per VIN)",
"Model 3",
"Model S",
"Model X",
"Model Y",
"Cybertruck",
),
"fr": T(
"Exécuter",
" (facultatif)",
"(non défini)",
"%1 • %2 °C à l'intérieur",
"Climatisation activée",
"Climatisation désactivée",
"Batterie %1 %%2",
" • En charge",
"Portes verrouillées",
"Portes déverrouillées",
"OK",
"code de sortie %1",
"Exécution de %1...",
"Attention",
"Klaxon",
"Appel de phares",
"Réveiller le véhicule",
"Climatisation",
"Activer la climatisation",
"Désactiver la climatisation",
"Régler la température",
"Sièges chauffants",
"Volant chauffant",
"Sièges et clim. auto",
"Ajouter préconditionnement programmé",
"Supprimer préconditionnement programmé",
"Recharge",
"Démarrer la recharge",
"Arrêter la recharge",
"Ouvrir la trappe de recharge",
"Fermer la trappe de recharge",
"Définir la limite de recharge",
"Définir le courant de recharge",
"Programmer la recharge",
"Annuler la recharge programmée",
"Ajouter une recharge programmée",
"Supprimer une recharge programmée",
"Verrouillage et sécurité",
"Verrouiller",
"Déverrouiller",
"Démarrage à distance (conduite sans clé)",
"Mode sentinelle",
"Activer le mode voiturier",
"Désactiver le mode voiturier",
"Activer le mode invité",
"Désactiver le mode invité",
"Effacer les données invité",
"Sécurisation auto (Model X)",
"Coffres et vitres",
"Ouvrir le coffre arrière",
"Actionner le coffre arrière",
"Fermer le coffre arrière",
"Ouvrir le coffre avant",
"Ouvrir le tonneau (Cybertruck)",
"Fermer le tonneau (Cybertruck)",
"Arrêter le tonneau (Cybertruck)",
"Entrouvrir les vitres",
"Fermer les vitres",
"Média",
"Lecture / Pause",
"Piste suivante",
"Piste précédente",
"Favori suivant",
"Favori précédent",
"Augmenter le volume",
"Diminuer le volume",
"Régler le volume",
"Logiciel",
"Démarrer la mise à jour logicielle",
"Annuler la mise à jour logicielle",
"Clés",
"Lister les clés enregistrées",
"Ajouter une clé",
"Supprimer une clé",
"Infos de session",
"Diagnostic",
"Ping du véhicule",
"Lire l'état du véhicule",
"État du contrôleur de caisse",
"Maintenir l'alimentation accessoires",
"Mode basse consommation",
"Le cœur de contrôle n'a pas démarré. Réinstallez l'appli, puis tirez vers le bas pour actualiser.",
"Le cœur de contrôle est trop ancien pour indiquer sa version. Réinstallez l'appli (%1), puis tirez vers le bas pour actualiser.",
"Versions incompatibles : appli %1, cœur %2. Réinstallez l'appli, puis tirez vers le bas pour actualiser.",
"Aucun VIN configuré",
"Clé prête",
"Pas de clé - touchez pour Paramètres / Jumelage",
" • en charge",
"• %1 °C",
"Mise à jour...",
"État indisponible (%1). Le véhicule dort peut-être - essayez Réveiller le véhicule (Attention), puis Actualiser l'état.",
"Tirez vers le bas pour actualiser l'état",
"Mis à jour à l'instant",
"Mis à jour il y a %1 min",
"Catégories",
"Envoyer la destination",
"Jumeler le véhicule",
"Paramètres",
"Actualiser",
"Actualiser l'état",
"Collez ou saisissez d'abord une destination.",
"Vérification...",
"Rien à envoyer.",
"Inutilisable : %1",
"Coordonnées %1, %2 — la navigation démarrera là.",
"Adresse « %1 » — recherchée par la voiture.",
"Échec de l'envoi : %1",
"Navigation auto",
"Destination",
"Collez adresse, coordonnées ou lien carte",
"Aperçu",
"Envoyer à la voiture",
"Notes",
"Utilise le Bluetooth, comme verrouiller/déverrouiller — la voiture doit être à portée, sans internet des deux côtés. Les coordonnées sont envoyées exactement ; adresses et liens sont recherchés par la voiture elle-même, les orthographes inhabituelles peuvent donc se résoudre différemment que sur le téléphone. Depuis les applis Android : copiez l'adresse ou le lien, puis collez-le ci-dessus.",
"Clé générée. Touchez « Jumeler le véhicule », puis posez la carte NFC sur la console centrale quand l'écran de la voiture le demande.",
"Échec de génération de la clé : %1",
"Jumelé.",
"Échec du jumelage : %1",
"Jumelage et clés",
"Renseignez d'abord le VIN dans les Paramètres. Générez ensuite une clé et jumlez-la à la voiture en BLE - vous devez être près du véhicule et poser la carte NFC sur la console centrale pour approuver.",
"Clé téléphone en démarrage...",
"Génération...",
"Générer une clé",
"En attente du tap NFC...",
"Jumeler le véhicule",
"Jumelage BLE demandé - approuvez sur l'écran tactile / la carte NFC maintenant.",
"Clés enregistrées",
"Lister les clés enregistrées",
"Chargement de la configuration...",
"Clé présente",
"Pas encore de clé - utilisez Jumeler le véhicule depuis le menu principal",
"Enregistré",
"Échec de l'enregistrement : %1",
"Paramètres",
"VIN du véhicule",
"VIN à 17 caractères",
"Modèle sur la page d'accueil",
"Auto sélectionne le modèle depuis le VIN",
"Nom de la clé",
"harbour-electric-eel",
"Délai de connexion",
" s",
"Délai de commande",
"Enregistrer",
"Jumelage et clés",
"À propos",
"Appli : ElectricEel %1   |   cœur : %2",
"(trop ancien / inconnu)",
"Le cœur de contrôle est trop ancien pour indiquer une version - réinstallez l'appli.",
"Incompatibilité : cœur %1 vs appli %2 - réinstallez l'appli.",
"Auto (depuis le VIN)",
"Model 3",
"Model S",
"Model X",
"Model Y",
"Cybertruck",
),
}


if __name__ == "__main__":
    write_all(LANGS)
