#!/usr/bin/env python3
"""Batch B: es pt pt_BR nl sv da. See fill-a.py / fill_common.py."""
import os
import sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from fill_common import write_all


def T(*items):
    return list(items)


LANGS = {
"es": T(
"Ejecutar",
" (opcional)",
"(sin definir)",
"%1 • %2 °C en el interior",
"Climatización activada",
"Climatización desactivada",
"Batería %1 %%2",
" • Cargando",
"Puertas bloqueadas",
"Puertas desbloqueadas",
"OK",
"código de salida %1",
"Ejecutando %1...",
"Atención",
"Claxon",
"Ráfagas",
"Despertar el vehículo",
"Climatización",
"Activar climatización",
"Desactivar climatización",
"Ajustar temperatura",
"Asientos calefactados",
"Volante calefactado",
"Asientos y clima automáticos",
"Añadir preacondicionamiento programado",
"Eliminar preacondicionamiento programado",
"Carga",
"Iniciar carga",
"Detener carga",
"Abrir puerto de carga",
"Cerrar puerto de carga",
"Definir límite de carga",
"Definir corriente de carga",
"Programar carga",
"Cancelar carga programada",
"Añadir carga programada",
"Eliminar carga programada",
"Bloqueo y seguridad",
"Bloquear",
"Desbloquear",
"Arranque remoto (conducción sin llave)",
"Modo centinela",
"Activar modo aparcacoches",
"Desactivar modo aparcacoches",
"Activar modo invitado",
"Desactivar modo invitado",
"Borrar datos de invitado",
"Asegurado auto (Model X)",
"Maleteros y ventanillas",
"Abrir maletero trasero",
"Mover maletero trasero",
"Cerrar maletero trasero",
"Abrir maletero delantero",
"Abrir tonneau (Cybertruck)",
"Cerrar tonneau (Cybertruck)",
"Detener tonneau (Cybertruck)",
"Ventilar ventanillas",
"Cerrar ventanillas",
"Multimedia",
"Reproducir / Pausa",
"Pista siguiente",
"Pista anterior",
"Favorito siguiente",
"Favorito anterior",
"Subir volumen",
"Bajar volumen",
"Ajustar volumen",
"Software",
"Iniciar actualización de software",
"Cancelar actualización de software",
"Llaves",
"Listar llaves registradas",
"Añadir llave",
"Eliminar llave",
"Info de sesión",
"Diagnóstico",
"Ping al vehículo",
"Leer estado del vehículo",
"Estado del controlador de carrocería",
"Mantener alimentación de accesorios",
"Modo de bajo consumo",
"El núcleo de control no pudo iniciarse. Reinstala la app y desliza hacia abajo para actualizar.",
"El núcleo de control es demasiado antiguo para informar su versión. Reinstala la app (%1) y desliza hacia abajo para actualizar.",
"No coinciden las versiones: app %1, núcleo %2. Reinstala la app y desliza hacia abajo para actualizar.",
"Ningún VIN configurado",
"Llave lista",
"Sin llave - toca para Ajustes / Vincular",
" • cargando",
"• %1 °C",
"Actualizando...",
"Estado no disponible (%1). El vehículo puede estar dormido - prueba Despertar el vehículo (Atención) y luego Actualizar estado.",
"Desliza hacia abajo para actualizar el estado",
"Actualizado ahora mismo",
"Actualizado hace %1 min",
"Categorías",
"Enviar destino",
"Vincular vehículo",
"Ajustes",
"Actualizar",
"Actualizar estado",
"Pega o escribe primero un destino.",
"Comprobando...",
"Nada que enviar.",
"No utilizable: %1",
"Coordenadas %1, %2 — la navegación empezará allí.",
"Dirección «%1» — la buscará el coche.",
"Envío fallido: %1",
"Navegación del coche",
"Destino",
"Pega dirección, coordenadas o enlace de mapa",
"Vista previa",
"Enviar al coche",
"Notas",
"Usa Bluetooth, como bloquear/desbloquear — el coche debe estar al alcance, sin internet en ningún lado. Las coordenadas se envían exactas; las direcciones y enlaces los busca el propio coche, así que una escritura inusual puede resolverse distinto que en el teléfono. Desde apps Android: copia la dirección o el enlace y pégalo arriba.",
"Llave generada. Toca «Vincular vehículo» y apoya la tarjeta NFC en la consola central cuando lo pida la pantalla del coche.",
"Falló la generación de la llave: %1",
"Vinculado.",
"Falló la vinculación: %1",
"Vinculación y llaves",
"Configura primero el VIN en Ajustes. Luego genera una llave y vincúlala al coche por BLE - debes estar junto al vehículo y apoyar la tarjeta NFC en la consola central para aprobar.",
"Llave de teléfono iniciando...",
"Generando...",
"Generar llave",
"Esperando toque NFC...",
"Vincular vehículo",
"Vinculación BLE solicitada - aprueba en la pantalla táctil / tarjeta NFC ahora.",
"Llaves registradas",
"Listar llaves registradas",
"Cargando configuración...",
"Llave presente",
"Aún sin llave - usa Vincular vehículo desde el menú principal",
"Guardado",
"Falló el guardado: %1",
"Ajustes",
"VIN del vehículo",
"VIN de 17 caracteres",
"Modelo en la portada",
"Auto selecciona el modelo desde el VIN",
"Nombre de la llave",
"harbour-electric-eel",
"Tiempo de conexión",
" s",
"Tiempo de comando",
"Guardar",
"Vinculación y llaves",
"Acerca de",
"App: ElectricEel %1   |   núcleo: %2",
"(demasiado antiguo / desconocido)",
"El núcleo de control es demasiado antiguo para informar una versión - reinstala la app.",
"No coinciden: núcleo %1 vs app %2 - reinstala la app.",
"Auto (desde el VIN)",
"Model 3",
"Model S",
"Model X",
"Model Y",
"Cybertruck",
),
"pt": T(
"Executar",
" (opcional)",
"(não definido)",
"%1 • %2 °C no interior",
"Climatização ligada",
"Climatização desligada",
"Bateria %1 %%2",
" • A carregar",
"Portas trancadas",
"Portas destrancadas",
"OK",
"código de saída %1",
"A executar %1...",
"Atenção",
"Buzina",
"Máximos",
"Acordar o veículo",
"Climatização",
"Ligar climatização",
"Desligar climatização",
"Definir temperatura",
"Bancos aquecidos",
"Volante aquecido",
"Bancos e clima automáticos",
"Adicionar pré-condicionamento agendado",
"Remover pré-condicionamento agendado",
"Carregamento",
"Iniciar carregamento",
"Parar carregamento",
"Abrir porta de carga",
"Fechar porta de carga",
"Definir limite de carga",
"Definir corrente de carga",
"Agendar carregamento",
"Cancelar carregamento agendado",
"Adicionar carregamento agendado",
"Remover carregamento agendado",
"Trancas e segurança",
"Trancar",
"Destrancar",
"Arranque remoto (condução sem chave)",
"Modo sentinela",
"Ativar modo manobrista",
"Desativar modo manobrista",
"Ativar modo convidado",
"Desativar modo convidado",
"Apagar dados de convidado",
"Proteção auto (Model X)",
"Bagageiras e vidros",
"Abrir bagageira traseira",
"Mover bagageira traseira",
"Fechar bagageira traseira",
"Abrir bagageira dianteira",
"Abrir tonneau (Cybertruck)",
"Fechar tonneau (Cybertruck)",
"Parar tonneau (Cybertruck)",
"Ventilar vidros",
"Fechar vidros",
"Multimédia",
"Reproduzir / Pausa",
"Faixa seguinte",
"Faixa anterior",
"Favorita seguinte",
"Favorita anterior",
"Aumentar volume",
"Diminuir volume",
"Definir volume",
"Software",
"Iniciar atualização de software",
"Cancelar atualização de software",
"Chaves",
"Listar chaves registadas",
"Adicionar chave",
"Remover chave",
"Info de sessão",
"Diagnóstico",
"Ping ao veículo",
"Ler estado do veículo",
"Estado do controlador da carroçaria",
"Manter alimentação de acessórios",
"Modo de baixo consumo",
"O núcleo de controlo não arrancou. Reinstala a app e puxa para baixo para atualizar.",
"O núcleo de controlo é demasiado antigo para indicar a versão. Reinstala a app (%1) e puxa para baixo para atualizar.",
"Versões incompatíveis: app %1, núcleo %2. Reinstala a app e puxa para baixo para atualizar.",
"Nenhum VIN configurado",
"Chave pronta",
"Sem chave - toca para Definições / Emparelhar",
" • a carregar",
"• %1 °C",
"A atualizar...",
"Estado indisponível (%1). O veículo pode estar adormecido - tenta Acordar o veículo (Atenção) e depois Atualizar estado.",
"Puxa para baixo para atualizar o estado",
"Atualizado agora",
"Atualizado há %1 min",
"Categorias",
"Enviar destino",
"Emparelhar veículo",
"Definições",
"Atualizar",
"Atualizar estado",
"Cola ou escreve primeiro um destino.",
"A verificar...",
"Nada a enviar.",
"Não utilizável: %1",
"Coordenadas %1, %2 — a navegação começará aí.",
"Morada «%1» — será procurada pelo carro.",
"Falha no envio: %1",
"Navegação do carro",
"Destino",
"Cola morada, coordenadas ou link de mapa",
"Pré-visualizar",
"Enviar para o carro",
"Notas",
"Usa Bluetooth, como trancar/destrancar — o carro tem de estar ao alcance, sem internet de nenhum lado. As coordenadas são enviadas exatas; moradas e links são procurados pelo próprio carro, por isso uma grafia invulgar pode resolver-se de forma diferente que no telefone. Desde apps Android: copia a morada ou o link e cola acima.",
"Chave gerada. Toca «Emparelhar veículo» e encosta o cartão NFC à consola central quando o ecrã do carro pedir.",
"Falha ao gerar a chave: %1",
"Emparelhado.",
"Falha no emparelhamento: %1",
"Emparelhamento e chaves",
"Define primeiro o VIN nas Definições. Depois gera uma chave e emparelha-a com o carro por BLE - tens de estar junto ao veículo e encostar o cartão NFC à consola central para aprovar.",
"Chave de telefone a iniciar...",
"A gerar...",
"Gerar chave",
"A aguardar toque NFC...",
"Emparelhar veículo",
"Emparelhamento BLE pedido - aprova no ecrã tátil / cartão NFC agora.",
"Chaves registadas",
"Listar chaves registadas",
"A carregar configuração...",
"Chave presente",
"Ainda sem chave - usa Emparelhar veículo no menu principal",
"Guardado",
"Falha ao guardar: %1",
"Definições",
"VIN do veículo",
"VIN de 17 caracteres",
"Modelo na capa",
"Auto seleciona o modelo pelo VIN",
"Nome da chave",
"harbour-electric-eel",
"Tempo de ligação",
" s",
"Tempo de comando",
"Guardar",
"Emparelhamento e chaves",
"Sobre",
"App: ElectricEel %1   |   núcleo: %2",
"(demasiado antigo / desconhecido)",
"O núcleo de controlo é demasiado antigo para indicar uma versão - reinstala a app.",
"Incompatíveis: núcleo %1 vs app %2 - reinstala a app.",
"Auto (pelo VIN)",
"Model 3",
"Model S",
"Model X",
"Model Y",
"Cybertruck",
),
"pt_BR": T(
"Executar",
" (opcional)",
"(não definido)",
"%1 • %2 °C internos",
"Climatização ligada",
"Climatização desligada",
"Bateria %1 %%2",
" • Carregando",
"Portas travadas",
"Portas destravadas",
"OK",
"código de saída %1",
"Executando %1...",
"Atenção",
"Buzina",
"Farol alto",
"Acordar o veículo",
"Climatização",
"Ligar climatização",
"Desligar climatização",
"Definir temperatura",
"Bancos aquecidos",
"Volante aquecido",
"Bancos e clima automáticos",
"Adicionar pré-condicionamento agendado",
"Remover pré-condicionamento agendado",
"Carregamento",
"Iniciar carregamento",
"Parar carregamento",
"Abrir portinhola de recarga",
"Fechar portinhola de recarga",
"Definir limite de carga",
"Definir corrente de carga",
"Agendar carregamento",
"Cancelar carregamento agendado",
"Adicionar carregamento agendado",
"Remover carregamento agendado",
"Travas e segurança",
"Travar",
"Destravar",
"Partida remota (direção sem chave)",
"Modo sentinela",
"Ativar modo manobrista",
"Desativar modo manobrista",
"Ativar modo visitante",
"Desativar modo visitante",
"Apagar dados de visitante",
"Proteção auto (Model X)",
"Porta-malas e vidros",
"Abrir porta-malas traseiro",
"Mover porta-malas traseiro",
"Fechar porta-malas traseiro",
"Abrir porta-malas dianteiro",
"Abrir tonneau (Cybertruck)",
"Fechar tonneau (Cybertruck)",
"Parar tonneau (Cybertruck)",
"Ventilar vidros",
"Fechar vidros",
"Mídia",
"Reproduzir / Pausar",
"Faixa seguinte",
"Faixa anterior",
"Favorita seguinte",
"Favorita anterior",
"Aumentar volume",
"Diminuir volume",
"Definir volume",
"Software",
"Iniciar atualização de software",
"Cancelar atualização de software",
"Chaves",
"Listar chaves registradas",
"Adicionar chave",
"Remover chave",
"Info de sessão",
"Diagnóstico",
"Ping no veículo",
"Ler estado do veículo",
"Estado do controlador da carroceria",
"Manter alimentação de acessórios",
"Modo de baixo consumo",
"O núcleo de controle não iniciou. Reinstale o app e puxe para baixo para atualizar.",
"O núcleo de controle é antigo demais para informar a versão. Reinstale o app (%1) e puxe para baixo para atualizar.",
"Versões incompatíveis: app %1, núcleo %2. Reinstale o app e puxe para baixo para atualizar.",
"Nenhum VIN configurado",
"Chave pronta",
"Sem chave - toque para Ajustes / Parear",
" • carregando",
"• %1 °C",
"Atualizando...",
"Estado indisponível (%1). O veículo pode estar dormindo - tente Acordar o veículo (Atenção) e depois Atualizar estado.",
"Puxe para baixo para atualizar o estado",
"Atualizado agora",
"Atualizado há %1 min",
"Categorias",
"Enviar destino",
"Parear veículo",
"Ajustes",
"Atualizar",
"Atualizar estado",
"Cole ou digite primeiro um destino.",
"Verificando...",
"Nada a enviar.",
"Não utilizável: %1",
"Coordenadas %1, %2 — a navegação começará aí.",
"Endereço «%1» — será procurado pelo carro.",
"Falha no envio: %1",
"Navegação do carro",
"Destino",
"Cole endereço, coordenadas ou link de mapa",
"Prévia",
"Enviar para o carro",
"Notas",
"Usa Bluetooth, como travar/destravar — o carro precisa estar ao alcance, sem internet de nenhum lado. As coordenadas são enviadas exatas; endereços e links são procurados pelo próprio carro, então uma grafia incomum pode resolver diferente do telefone. De apps Android: copie o endereço ou o link e cole acima.",
"Chave gerada. Toque «Parear veículo» e encoste o cartão NFC no console central quando a tela do carro pedir.",
"Falha ao gerar a chave: %1",
"Pareado.",
"Falha no pareamento: %1",
"Pareamento e chaves",
"Defina primeiro o VIN nos Ajustes. Depois gere uma chave e pareie com o carro por BLE - você precisa estar junto ao veículo e encostar o cartão NFC no console central para aprovar.",
"Chave de telefone iniciando...",
"Gerando...",
"Gerar chave",
"Aguardando toque NFC...",
"Parear veículo",
"Pareamento BLE solicitado - aprove na tela tátil / cartão NFC agora.",
"Chaves registradas",
"Listar chaves registradas",
"Carregando configuração...",
"Chave presente",
"Ainda sem chave - use Parear veículo no menu principal",
"Salvo",
"Falha ao salvar: %1",
"Ajustes",
"VIN do veículo",
"VIN de 17 caracteres",
"Modelo na capa",
"Auto seleciona o modelo pelo VIN",
"Nome da chave",
"harbour-electric-eel",
"Tempo de conexão",
" s",
"Tempo de comando",
"Salvar",
"Pareamento e chaves",
"Sobre",
"App: ElectricEel %1   |   núcleo: %2",
"(antigo demais / desconhecido)",
"O núcleo de controle é antigo demais para informar uma versão - reinstale o app.",
"Incompatíveis: núcleo %1 vs app %2 - reinstale o app.",
"Auto (pelo VIN)",
"Model 3",
"Model S",
"Model X",
"Model Y",
"Cybertruck",
),
"nl": T(
"Uitvoeren",
" (optioneel)",
"(niet ingesteld)",
"%1 • %2°C binnen",
"Klimaat aan",
"Klimaat uit",
"%1% accu%2",
" • Aan het laden",
"Deuren vergrendeld",
"Deuren ontgrendeld",
"OK",
"exitcode %1",
"%1 uitvoeren...",
"Attentie",
"Claxon",
"Seinen met koplampen",
"Voertuig wekken",
"Klimaat",
"Klimaat aan",
"Klimaat uit",
"Temperatuur instellen",
"Stoelverwarming",
"Stuurverwarming",
"Stoel & klimaat automatisch",
"Voorconditionering plannen",
"Voorconditionering verwijderen",
"Opladen",
"Laden starten",
"Laden stoppen",
"Laadklep openen",
"Laadklep sluiten",
"Laadlimiet instellen",
"Laadstroom instellen",
"Laden plannen",
"Gepland laden annuleren",
"Laadschema toevoegen",
"Laadschema verwijderen",
"Vergrendeling & beveiliging",
"Vergrendelen",
"Ontgrendelen",
"Start op afstand (sleutelloos rijden)",
"Schildwachtmodus",
"Valetmodus aan",
"Valetmodus uit",
"Gastmodus aan",
"Gastmodus uit",
"Gastgegevens wissen",
"Auto-beveiligen (Model X)",
"Koffers & ruiten",
"Achterklep openen",
"Achterklep bewegen",
"Achterklep sluiten",
"Voorklep openen",
"Tonneau openen (Cybertruck)",
"Tonneau sluiten (Cybertruck)",
"Tonneau stoppen (Cybertruck)",
"Ruiten ventileren",
"Ruiten sluiten",
"Media",
"Afspelen / Pauze",
"Volgende nummer",
"Vorig nummer",
"Volgende favoriet",
"Vorige favoriet",
"Volume omhoog",
"Volume omlaag",
"Volume instellen",
"Software",
"Software-update starten",
"Software-update annuleren",
"Sleutels",
"Geregistreerde sleutels tonen",
"Sleutel toevoegen",
"Sleutel verwijderen",
"Sessie-info",
"Diagnose",
"Voertuig pingen",
"Voertuigstatus ophalen",
"Carrosserieregelunit-status",
"Accessoirevoeding behouden",
"Energiebesparende modus",
"De besturingskern kon niet starten. Installeer de app opnieuw en trek omlaag om te vernieuwen.",
"De besturingskern is te oud om zijn versie te melden. Installeer de app (%1) opnieuw en trek omlaag om te vernieuwen.",
"Versieconflict: app %1, kern %2. Installeer de app opnieuw en trek omlaag om te vernieuwen.",
"Geen VIN ingesteld",
"Sleutel klaar",
"Geen sleutel - tik voor Instellingen / Koppelen",
" • aan het laden",
"• %1°C",
"Bezig met bijwerken...",
"Status niet beschikbaar (%1). Het voertuig slaapt mogelijk - probeer Voertuig wekken (Attentie) en dan Status vernieuwen.",
"Trek omlaag om de status te vernieuwen",
"Zojuist bijgewerkt",
"%1 min geleden bijgewerkt",
"Categorieën",
"Bestemming verzenden",
"Voertuig koppelen",
"Instellingen",
"Vernieuwen",
"Status vernieuwen",
"Plak of typ eerst een bestemming.",
"Controleren...",
"Niets te verzenden.",
"Niet bruikbaar: %1",
"Coördinaten %1, %2 — navigatie start daar.",
"Adres «%1» — wordt door de auto opgezocht.",
"Verzenden mislukt: %1",
"Autonavigatie",
"Bestemming",
"Plak adres, coördinaten of kaartlink",
"Voorbeeld",
"Naar auto verzenden",
"Opmerkingen",
"Gebruikt Bluetooth, zoals vergrendelen/ontgrendelen — de auto moet binnen bereik zijn, geen internet nodig. Coördinaten worden exact verzonden; adressen en links zoekt de auto zelf op, ongebruikelijke spelling kan dus anders uitpakken dan op de telefoon. Vanuit Android-apps: kopieer het adres of de link en plak het hierboven.",
"Sleutel aangemaakt. Tik op «Voertuig koppelen» en houd de NFC-kaart tegen de middenconsole wanneer het autoscherm erom vraagt.",
"Aanmaken sleutel mislukt: %1",
"Gekoppeld.",
"Koppelen mislukt: %1",
"Koppelen & sleutels",
"Stel eerst de VIN in bij Instellingen. Maak dan een sleutel en koppel die via BLE aan de auto - sta naast het voertuig en houd de NFC-kaart tegen de middenconsole om goed te keuren.",
"Telefoonsleutel start...",
"Bezig met aanmaken...",
"Sleutel aanmaken",
"Wachten op NFC-tik...",
"Voertuig koppelen",
"BLE-koppeling aangevraagd - keur nu goed op het touchscreen / de NFC-kaart.",
"Geregistreerde sleutels",
"Geregistreerde sleutels tonen",
"Configuratie laden...",
"Sleutel aanwezig",
"Nog geen sleutel - gebruik Voertuig koppelen in het hoofdmenu",
"Opgeslagen",
"Opslaan mislukt: %1",
"Instellingen",
"Voertuig-VIN",
"17-tekens VIN",
"Automodel op voorpagina",
"Auto kiest het model aan de hand van de VIN",
"Sleutelnaam",
"harbour-electric-eel",
"Verbindings-timeout",
" s",
"Opdracht-timeout",
"Opslaan",
"Koppelen & sleutels",
"Over",
"App: ElectricEel %1   |   kern: %2",
"(te oud / onbekend)",
"De besturingskern is te oud om een versie te melden - installeer de app opnieuw.",
"Versieconflict: kern %1 vs app %2 - installeer de app opnieuw.",
"Auto (via VIN)",
"Model 3",
"Model S",
"Model X",
"Model Y",
"Cybertruck",
),
"sv": T(
"Kör",
" (valfritt)",
"(inte inställt)",
"%1 • %2 °C inne",
"Klimat på",
"Klimat av",
"%1 % batteri%2",
" • Laddar",
"Dörrar låsta",
"Dörrar olåsta",
"OK",
"slutkod %1",
"Kör %1...",
"Uppmärksamhet",
"Tuta",
"Blinka med strålkastarna",
"Väck fordonet",
"Klimat",
"Sätt på klimatet",
"Stäng av klimatet",
"Ställ in temperatur",
"Stolsvärme",
"Rattvärme",
"Stol & klimat automatiskt",
"Lägg till schemalagd förkonditionering",
"Ta bort schemalagd förkonditionering",
"Laddning",
"Starta laddning",
"Stoppa laddning",
"Öppna laddluckan",
"Stäng laddluckan",
"Ställ in laddgräns",
"Ställ in laddström",
"Schemalägg laddning",
"Avbryt schemalagd laddning",
"Lägg till laddschema",
"Ta bort laddschema",
"Lås & säkerhet",
"Lås",
"Lås upp",
"Fjärrstart (nyckellös körning)",
"Vaktläge",
"Valetläge på",
"Valetläge av",
"Gästläge på",
"Gästläge av",
"Rensa gästdata",
"Autosäkring (Model X)",
"Bagage & fönster",
"Öppna bakluckan",
"Flytta bakluckan",
"Stäng bakluckan",
"Öppna frunken",
"Öppna tonneau (Cybertruck)",
"Stäng tonneau (Cybertruck)",
"Stoppa tonneau (Cybertruck)",
"Vädra fönstren",
"Stäng fönstren",
"Media",
"Spela / Pausa",
"Nästa spår",
"Föregående spår",
"Nästa favorit",
"Föregående favorit",
"Höj volymen",
"Sänk volymen",
"Ställ in volymen",
"Programvara",
"Starta programuppdatering",
"Avbryt programuppdatering",
"Nycklar",
"Lista registrerade nycklar",
"Lägg till nyckel",
"Ta bort nyckel",
"Sessionsinfo",
"Diagnostik",
"Pinga fordonet",
"Hämta fordonsstatus",
"Kaross Styrenhetsstatus",
"Behåll tillbehörsström",
"Energisparläge",
"Styrkärnan kunde inte starta. Installera om appen och dra nedåt för att uppdatera.",
"Styrkärnan är för gammal för att rapportera sin version. Installera om appen (%1) och dra nedåt för att uppdatera.",
"Versionskonflikt: app %1, kärna %2. Installera om appen och dra nedåt för att uppdatera.",
"Ingen VIN konfigurerad",
"Nyckel klar",
"Ingen nyckel - tryck för Inställningar / Parkoppla",
" • laddar",
"• %1 °C",
"Uppdaterar...",
"Status otillgänglig (%1). Fordonet sover kanske - prova Väck fordonet (Uppmärksamhet) och sedan Uppdatera status.",
"Dra nedåt för att uppdatera statusen",
"Uppdaterad just nu",
"Uppdaterad för %1 min sedan",
"Kategorier",
"Skicka destination",
"Parkoppla fordon",
"Inställningar",
"Uppdatera",
"Uppdatera status",
"Klistra in eller skriv en destination först.",
"Kontrollerar...",
"Inget att skicka.",
"Kan inte användas: %1",
"Koordinater %1, %2 — navigeringen startar där.",
"Adress ”%1” — bilen söker upp den.",
"Sändning misslyckades: %1",
"Bilnavigation",
"Destination",
"Klistra in adress, koordinater eller kartlänk",
"Förhandsvisning",
"Skicka till bilen",
"Anteckningar",
"Använder Bluetooth, som lås/lås upp — bilen måste vara inom räckhåll, inget internet behövs. Koordinater skickas exakt; adresser och länkar söker bilen själv upp, så ovanliga stavningar kan tolkas annorlunda än på telefonen. Från Android-appar: kopiera adressen eller länken och klistra in ovan.",
"Nyckel skapad. Tryck på ”Parkoppla fordon” och håll NFC-kortet mot mittkonsolen när bilskärmen ber om det.",
"Nyckelsgenerering misslyckades: %1",
"Parkopplad.",
"Parkoppling misslyckades: %1",
"Parkoppling & nycklar",
"Ställ först in VIN i Inställningar. Skapa sedan en nyckel och parkoppla den med bilen via BLE - stå bredvid fordonet och håll NFC-kortet mot mittkonsolen för att godkänna.",
"Telefonnyckel startar...",
"Genererar...",
"Generera nyckel",
"Väntar på NFC-tryck...",
"Parkoppla fordon",
"BLE-parkoppling begärd - godkänn på pekskärmen / NFC-kortet nu.",
"Registrerade nycklar",
"Lista registrerade nycklar",
"Läser in konfiguration...",
"Nyckel finns",
"Ingen nyckel ännu - använd Parkoppla fordon i huvudmenyn",
"Sparad",
"Sparande misslyckades: %1",
"Inställningar",
"Fordonets VIN",
"17-teckens VIN",
"Bilmodell på förstasidan",
"Auto väljer modellen från VIN",
"Nyckelnamn",
"harbour-electric-eel",
"Anslutningstimeout",
" s",
"Kommandotimeout",
"Spara",
"Parkoppling & nycklar",
"Om",
"App: ElectricEel %1   |   kärna: %2",
"(för gammal / okänd)",
"Styrkärnan är för gammal för att rapportera en version - installera om appen.",
"Versionskonflikt: kärna %1 vs app %2 - installera om appen.",
"Auto (från VIN)",
"Model 3",
"Model S",
"Model X",
"Model Y",
"Cybertruck",
),
"da": T(
"Kør",
" (valgfri)",
"(ikke angivet)",
"%1 • %2 °C inde",
"Klima til",
"Klima fra",
"%1 % batteri%2",
" • Oplader",
"Døre låst",
"Døre ulåst",
"OK",
"exitkode %1",
"Kører %1...",
"Opmærksomhed",
"Dyt",
"Blink med forlygterne",
"Væk køretøjet",
"Klima",
"Tænd klima",
"Sluk klima",
"Indstil temperatur",
"Sædevarme",
"Ratvarme",
"Sæde & klima automatisk",
"Tilføj planlagt forkonditionering",
"Fjern planlagt forkonditionering",
"Opladning",
"Start opladning",
"Stop opladning",
"Åbn ladeklap",
"Luk ladeklap",
"Indstil opladningsgrænse",
"Indstil ladestrøm",
"Planlæg opladning",
"Annuller planlagt opladning",
"Tilføj opladningsplan",
"Fjern opladningsplan",
"Lås & sikkerhed",
"Lås",
"Lås op",
"Fjernstart (nøglefri kørsel)",
"Vagttilstand",
"Valettilstand til",
"Valettilstand fra",
"Gæstetilstand til",
"Gæstetilstand fra",
"Slet gæstedata",
"Autosikring (Model X)",
"Bagagerum & vinduer",
"Åbn bagklap",
"Bevæg bagklap",
"Luk bagklap",
"Åbn frunk",
"Åbn tonneau (Cybertruck)",
"Luk tonneau (Cybertruck)",
"Stop tonneau (Cybertruck)",
"Luft ud ad vinduerne",
"Luk vinduerne",
"Medier",
"Afspil / Pause",
"Næste nummer",
"Forrige nummer",
"Næste favorit",
"Forrige favorit",
"Skru op",
"Skru ned",
"Indstil lydstyrke",
"Software",
"Start softwareopdatering",
"Annuller softwareopdatering",
"Nøgler",
"Vis registrerede nøgler",
"Tilføj nøgle",
"Fjern nøgle",
"Sessionsinfo",
"Diagnostik",
"Ping køretøjet",
"Hent køretøjsstatus",
"Status for karrosseristyreenhed",
"Behold tilbehørsstrøm",
"Strømsparetilstand",
"Styringskernen kunne ikke starte. Geninstaller appen og træk ned for at opdatere.",
"Styringskernen er for gammel til at rapportere sin version. Geninstaller appen (%1) og træk ned for at opdatere.",
"Versionskonflikt: app %1, kerne %2. Geninstaller appen og træk ned for at opdatere.",
"Ingen VIN konfigureret",
"Nøgle klar",
"Ingen nøgle - tryk for Indstillinger / Parring",
" • oplader",
"• %1 °C",
"Opdaterer...",
"Status ikke tilgængelig (%1). Køretøjet sover måske - prøv Væk køretøjet (Opmærksomhed) og derefter Opdater status.",
"Træk ned for at opdatere status",
"Opdateret lige nu",
"Opdateret for %1 min siden",
"Kategorier",
"Send destination",
"Par køretøj",
"Indstillinger",
"Opdater",
"Opdater status",
"Indsæt eller skriv først en destination.",
"Kontrollerer...",
"Intet at sende.",
"Kan ikke bruges: %1",
"Koordinater %1, %2 — navigationen starter der.",
"Adresse ”%1” — bilen slår den op.",
"Afsendelse mislykkedes: %1",
"Bilnavigation",
"Destination",
"Indsæt adresse, koordinater eller kortlink",
"Forhåndsvisning",
"Send til bilen",
"Noter",
"Bruger Bluetooth, som lås/lås op — bilen skal være inden for rækkevidde, intet internet nødvendigt. Koordinater sendes nøjagtigt; adresser og links slår bilen selv op, så usædvanlige stavemåder kan tolkes anderledes end på telefonen. Fra Android-apps: kopiér adressen eller linket og indsæt ovenfor.",
"Nøgle oprettet. Tryk på ”Par køretøj” og hold NFC-kortet mod midterkonsollen, når bilskærmen beder om det.",
"Oprettelse af nøgle mislykkedes: %1",
"Parret.",
"Parring mislykkedes: %1",
"Parring & nøgler",
"Indstil først VIN i Indstillinger. Opret derefter en nøgle og par den med bilen via BLE - stå ved køretøjet og hold NFC-kortet mod midterkonsollen for at godkende.",
"Telefonnøgle starter...",
"Genererer...",
"Generer nøgle",
"Venter på NFC-tryk...",
"Par køretøj",
"BLE-parring anmodet - godkend på touchskærmen / NFC-kortet nu.",
"Registrerede nøgler",
"Vis registrerede nøgler",
"Indlæser konfiguration...",
"Nøgle findes",
"Ingen nøgle endnu - brug Par køretøj i hovedmenuen",
"Gemt",
"Lagring mislykkedes: %1",
"Indstillinger",
"Køretøjets VIN",
"17-tegns VIN",
"Bilmodel på forsiden",
"Auto vælger modellen ud fra VIN",
"Nøglenavn",
"harbour-electric-eel",
"Forbindelsestimeout",
" s",
"Kommandotimeout",
"Gem",
"Parring & nøgler",
"Om",
"App: ElectricEel %1   |   kerne: %2",
"(for gammel / ukendt)",
"Styringskernen er for gammel til at rapportere en version - geninstaller appen.",
"Versionskonflikt: kerne %1 vs app %2 - geninstaller appen.",
"Auto (fra VIN)",
"Model 3",
"Model S",
"Model X",
"Model Y",
"Cybertruck",
),
}
if __name__ == "__main__":
    write_all(LANGS)
