#!/usr/bin/env python3
"""Batch E: ru uk tr tt et vi. See fill-a.py / fill_common.py."""
import os
import sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from fill_common import write_all


def T(*items):
    return list(items)


LANGS = {
"ru": T(
"Выполнить",
" (необязательно)",
"(не задано)",
"%1 • %2 °C в салоне",
"Климат включён",
"Климат выключен",
"%1% заряда%2",
" • Заряжается",
"Двери заблокированы",
"Двери разблокированы",
"OK",
"код выхода %1",
"Выполнение %1...",
"Внимание",
"Сигнал",
"Мигание фарами",
"Разбудить автомобиль",
"Климат",
"Включить климат",
"Выключить климат",
"Задать температуру",
"Подогрев сидений",
"Подогрев руля",
"Сиденья и климат автоматически",
"Добавить запланированную подготовку",
"Удалить запланированную подготовку",
"Зарядка",
"Начать зарядку",
"Остановить зарядку",
"Открыть порт зарядки",
"Закрыть порт зарядки",
"Задать лимит зарядки",
"Задать ток зарядки",
"Запланировать зарядку",
"Отменить запланированную зарядку",
"Добавить график зарядки",
"Удалить график зарядки",
"Замки и безопасность",
"Заблокировать",
"Разблокировать",
"Удалённый запуск (езда без ключа)",
"Режим Sentry",
"Включить режим Valet",
"Выключить режим Valet",
"Включить гостевой режим",
"Выключить гостевой режим",
"Стереть гостевые данные",
"Автоохрана (Model X)",
"Багажники и окна",
"Открыть задний багажник",
"Привести в движение задний багажник",
"Закрыть задний багажник",
"Открыть передний багажник",
"Открыть tonneau (Cybertruck)",
"Закрыть tonneau (Cybertruck)",
"Остановить tonneau (Cybertruck)",
"Проветрить окна",
"Закрыть окна",
"Медиа",
"Играть / Пауза",
"Следующий трек",
"Предыдущий трек",
"Следующее избранное",
"Предыдущее избранное",
"Громче",
"Тише",
"Задать громкость",
"ПО",
"Начать обновление ПО",
"Отменить обновление ПО",
"Ключи",
"Список зарегистрированных ключей",
"Добавить ключ",
"Удалить ключ",
"Информация о сессии",
"Диагностика",
"Пинг автомобиля",
"Прочитать состояние автомобиля",
"Состояние блока управления кузовом",
"Сохранять питание аксессуаров",
"Экорежим",
"Управляющее ядро не запустилось. Переустановите приложение и потяните вниз для обновления.",
"Управляющее ядро слишком старое и не сообщает версию. Переустановите приложение (%1) и потяните вниз для обновления.",
"Несовпадение версий: приложение %1, ядро %2. Переустановите приложение и потяните вниз для обновления.",
"VIN не настроен",
"Ключ готов",
"Нет ключа — нажмите для Настройки / Сопряжение",
" • заряжается",
"• %1 °C",
"Обновление...",
"Состояние недоступно (%1). Автомобиль, возможно, спит — попробуйте Разбудить автомобиль (Внимание), затем Обновить состояние.",
"Потяните вниз, чтобы обновить состояние",
"Обновлено только что",
"Обновлено %1 мин назад",
"Категории",
"Отправить пункт назначения",
"Сопрячь автомобиль",
"Настройки",
"Обновить",
"Обновить состояние",
"Сначала вставьте или введите пункт назначения.",
"Проверка...",
"Нечего отправлять.",
"Нельзя использовать: %1",
"Координаты %1, %2 — навигация начнётся там.",
"Адрес «%1» — автомобиль найдёт его сам.",
"Отправка не удалась: %1",
"Навигация автомобиля",
"Пункт назначения",
"Вставьте адрес, координаты или ссылку на карту",
"Предпросмотр",
"Отправить в автомобиль",
"Примечания",
"Используется Bluetooth, как блокировка/разблокировка — автомобиль должен быть в радиусе действия, интернет не нужен. Координаты отправляются точно; адреса и ссылки автомобиль ищет сам, поэтому необычное написание может распознаться иначе, чем в телефоне. Из Android-приложений: скопируйте адрес или ссылку и вставьте выше.",
"Ключ создан. Нажмите «Сопрячь автомобиль» и приложите NFC-карту к центральной консоли, когда попросит экран автомобиля.",
"Не удалось создать ключ: %1",
"Сопряжено.",
"Сопряжение не удалось: %1",
"Сопряжение и ключи",
"Сначала задайте VIN в Настройках. Затем создайте ключ и сопрягите его с автомобилем по BLE — стойте рядом с автомобилем и приложите NFC-карту к центральной консоли для подтверждения.",
"Ключ телефона запускается...",
"Создание...",
"Создать ключ",
"Ожидание касания NFC...",
"Сопрячь автомобиль",
"Запрошено сопряжение BLE — подтвердите на сенсорном экране / NFC-карте.",
"Зарегистрированные ключи",
"Список зарегистрированных ключей",
"Загрузка конфигурации...",
"Ключ существует",
"Ключа пока нет — используйте Сопрячь автомобиль в главном меню",
"Сохранено",
"Не удалось сохранить: %1",
"Настройки",
"VIN автомобиля",
"17-значный VIN",
"Модель авто на главной",
"Авто выбирает модель по VIN",
"Имя ключа",
"harbour-electric-eel",
"Таймаут подключения",
" с",
"Таймаут команды",
"Сохранить",
"Сопряжение и ключи",
"О программе",
"Приложение: ElectricEel %1   |   ядро: %2",
"(слишком старое / неизвестно)",
"Управляющее ядро слишком старое и не сообщает версию — переустановите приложение.",
"Несовпадение: ядро %1 против приложения %2 — переустановите приложение.",
"Авто (по VIN)",
"Model 3",
"Model S",
"Model X",
"Model Y",
"Cybertruck",
),
"uk": T(
"Виконати",
" (необов'язково)",
"(не задано)",
"%1 • %2 °C у салоні",
"Клімат увімкнено",
"Клімат вимкнено",
"%1% заряду%2",
" • Заряджається",
"Двері заблоковано",
"Двері розблоковано",
"OK",
"код виходу %1",
"Виконання %1...",
"Увага",
"Сигнал",
"Миготіння фарами",
"Розбудити автомобіль",
"Клімат",
"Увімкнути клімат",
"Вимкнути клімат",
"Задати температуру",
"Підігрів сидінь",
"Підігрів керма",
"Сидіння та клімат автоматично",
"Додати заплановану підготовку",
"Видалити заплановану підготовку",
"Заряджання",
"Почати заряджання",
"Зупинити заряджання",
"Відкрити порт заряджання",
"Закрити порт заряджання",
"Задати ліміт заряджання",
"Задати струм заряджання",
"Запланувати заряджання",
"Скасувати заплановане заряджання",
"Додати графік заряджання",
"Видалити графік заряджання",
"Замки та безпека",
"Заблокувати",
"Розблокувати",
"Віддалений запуск (їзда без ключа)",
"Режим Sentry",
"Увімкнути режим Valet",
"Вимкнути режим Valet",
"Увімкнути гостьовий режим",
"Вимкнути гостьовий режим",
"Стерти гостьові дані",
"Автозахист (Model X)",
"Багажники та вікна",
"Відкрити задній багажник",
"Рухати заднім багажником",
"Закрити задній багажник",
"Відкрити передній багажник",
"Відкрити tonneau (Cybertruck)",
"Закрити tonneau (Cybertruck)",
"Зупинити tonneau (Cybertruck)",
"Провітрити вікна",
"Закрити вікна",
"Медіа",
"Грати / Пауза",
"Наступний трек",
"Попередній трек",
"Наступне обране",
"Попереднє обране",
"Голосніше",
"Тихше",
"Задати гучність",
"ПЗ",
"Почати оновлення ПЗ",
"Скасувати оновлення ПЗ",
"Ключі",
"Список зареєстрованих ключів",
"Додати ключ",
"Видалити ключ",
"Інформація про сесію",
"Діагностика",
"Пінг автомобіля",
"Прочитати стан автомобіля",
"Стан блока керування кузовом",
"Зберігати живлення аксесуарів",
"Екорежим",
"Керувальне ядро не запустилось. Перевстановіть застосунок і потягніть вниз для оновлення.",
"Керувальне ядро застаре і не повідомляє версію. Перевстановіть застосунок (%1) і потягніть вниз для оновлення.",
"Невідповідність версій: застосунок %1, ядро %2. Перевстановіть застосунок і потягніть вниз для оновлення.",
"VIN не налаштовано",
"Ключ готовий",
"Немає ключа — натисніть для Налаштування / Сполучення",
" • заряджається",
"• %1 °C",
"Оновлення...",
"Стан недоступний (%1). Автомобіль, можливо, спить — спробуйте Розбудити автомобіль (Увага), потім Оновити стан.",
"Потягніть вниз, щоб оновити стан",
"Оновлено щойно",
"Оновлено %1 хв тому",
"Категорії",
"Надіслати пункт призначення",
"Спарувати автомобіль",
"Налаштування",
"Оновити",
"Оновити стан",
"Спочатку вставте або введіть пункт призначення.",
"Перевірка...",
"Немає чого надсилати.",
"Не можна використати: %1",
"Координати %1, %2 — навігація почнеться там.",
"Адреса «%1» — автомобіль знайде її сам.",
"Надсилання не вдалося: %1",
"Навігація автомобіля",
"Пункт призначення",
"Вставте адресу, координати або посилання на мапу",
"Попередній перегляд",
"Надіслати в автомобіль",
"Примітки",
"Використовується Bluetooth, як блокування/розблокування — автомобіль має бути в радіусі дії, інтернет не потрібен. Координати надсилаються точно; адреси й посилання автомобіль шукає сам, тож незвичне написання може розпізнатися інакше, ніж у телефоні. З Android-застосунків: скопіюйте адресу або посилання та вставте вище.",
"Ключ створено. Натисніть «Спарувати автомобіль» і прикладіть NFC-картку до центральної консолі, коли попросить екран автомобіля.",
"Не вдалося створити ключ: %1",
"Спарковано.",
"Спарювання не вдалося: %1",
"Спарювання та ключі",
"Спочатку задайте VIN у Налаштуваннях. Потім створіть ключ і спаруйте його з автомобілем через BLE — стійте поруч з автомобілем і прикладіть NFC-картку до центральної консолі для підтвердження.",
"Ключ телефона запускається...",
"Створення...",
"Створити ключ",
"Очікування дотику NFC...",
"Спарувати автомобіль",
"Запитано спарювання BLE — підтвердьте на сенсорному екрані / NFC-картці.",
"Зареєстровані ключі",
"Список зареєстрованих ключів",
"Завантаження конфігурації...",
"Ключ існує",
"Ключа поки немає — скористайтеся Спарувати автомобіль у головному меню",
"Збережено",
"Не вдалося зберегти: %1",
"Налаштування",
"VIN автомобіля",
"17-значний VIN",
"Модель авто на головній",
"Авто обирає модель за VIN",
"Ім'я ключа",
"harbour-electric-eel",
"Таймаут підключення",
" с",
"Таймаут команди",
"Зберегти",
"Спарювання та ключі",
"Про програму",
"Застосунок: ElectricEel %1   |   ядро: %2",
"(застаріле / невідомо)",
"Керувальне ядро застаріле і не повідомляє версію — перевстановіть застосунок.",
"Невідповідність: ядро %1 проти застосунку %2 — перевстановіть застосунок.",
"Авто (за VIN)",
"Model 3",
"Model S",
"Model X",
"Model Y",
"Cybertruck",
),
"tr": T(
"Çalıştır",
" (isteğe bağlı)",
"(ayarlanmadı)",
"%1 • %2 °C içeride",
"Klima açık",
"Klima kapalı",
"%1 % pil%2",
" • Şarj oluyor",
"Kapılar kilitli",
"Kapılar kilitsiz",
"OK",
"çıkış kodu %1",
"%1 çalıştırılıyor...",
"Dikkat",
"Korna",
"Farları yakıp söndürme",
"Aracı uyandır",
"Klima",
"Klimayı aç",
"Klimayı kapat",
"Sıcaklığı ayarla",
"Koltuk ısıtma",
"Direksiyon ısıtma",
"Koltuk ve klima otomatik",
"Planlı ön koşullandırma ekle",
"Planlı ön koşullandırmayı kaldır",
"Şarj",
"Şarjı başlat",
"Şarjı durdur",
"Şarj portunu aç",
"Şarj portunu kapat",
"Şarj limitini ayarla",
"Şarj akımını ayarla",
"Şarjı zamanla",
"Zamanlanmış şarjı iptal et",
"Şarj programı ekle",
"Şarj programını kaldır",
"Kilitler ve güvenlik",
"Kilitle",
"Kilidi aç",
"Uzaktan çalıştırma (anahtarsız sürüş)",
"Nöbetçi modu",
"Vale modu aç",
"Vale modu kapat",
"Misafir modu aç",
"Misafir modu kapat",
"Misafir verilerini sil",
"Otomatik koruma (Model X)",
"Bagajlar ve camlar",
"Arka bagajı aç",
"Arka bagajı hareket ettir",
"Arka bagajı kapat",
"Ön bagajı aç",
"Tonneau aç (Cybertruck)",
"Tonneau kapat (Cybertruck)",
"Tonneau durdur (Cybertruck)",
"Camları havalandır",
"Camları kapat",
"Medya",
"Oynat / Duraklat",
"Sonraki parça",
"Önceki parça",
"Sonraki favori",
"Önceki favori",
"Sesi aç",
"Sesi kıs",
"Ses düzeyini ayarla",
"Yazılım",
"Yazılım güncellemesini başlat",
"Yazılım güncellemesini iptal et",
"Anahtarlar",
"Kayıtlı anahtarları listele",
"Anahtar ekle",
"Anahtar kaldır",
"Oturum bilgisi",
"Tanılama",
"Araca ping gönder",
"Araç durumunu oku",
"Gövde kontrol ünitesi durumu",
"Aksesuar gücünü koru",
"Düşük güç modu",
"Kontrol çekirdeği başlatılamadı. Uygulamayı yeniden yükleyin ve yenilemek için aşağı çekin.",
"Kontrol çekirdeği sürüm bildiremeyecek kadar eski. Uygulamayı (%1) yeniden yükleyin ve yenilemek için aşağı çekin.",
"Sürüm uyumsuzluğu: uygulama %1, çekirdek %2. Uygulamayı yeniden yükleyin ve yenilemek için aşağı çekin.",
"VIN yapılandırılmadı",
"Anahtar hazır",
"Anahtar yok - Ayarlar / Eşleştirme için dokunun",
" • şarj oluyor",
"• %1 °C",
"Güncelleniyor...",
"Durum kullanılamıyor (%1). Araç uyuyor olabilir - Aracı uyandır (Dikkat) deneyin, sonra Durumu yenileyin.",
"Durumu yenilemek için aşağı çekin",
"Az önce güncellendi",
"%1 dk önce güncellendi",
"Kategoriler",
"Hedef gönder",
"Aracı eşleştir",
"Ayarlar",
"Yenile",
"Durumu yenile",
"Önce bir hedef yapıştırın veya yazın.",
"Denetleniyor...",
"Gönderilecek bir şey yok.",
"Kullanılamaz: %1",
"Koordinatlar %1, %2 — navigasyon orada başlayacak.",
"Adres “%1” — araç bulacak.",
"Gönderme başarısız: %1",
"Araç navigasyonu",
"Hedef",
"Adres, koordinat veya harita bağlantısı yapıştırın",
"Önizleme",
"Araca gönder",
"Notlar",
"Kilit kilitleme/açma gibi Bluetooth kullanır — araç menzil içinde olmalı, internet gerekmez. Koordinatlar aynen gönderilir; adresleri ve bağlantıları araç kendisi bulur, bu yüzden alışılmadık yazımlar telefondakinden farklı çözülebilir. Android uygulamalarından: adresi veya bağlantıyı kopyalayıp yukarıya yapıştırın.",
"Anahtar oluşturuldu. “Aracı eşleştir”e dokunun ve araç ekranı istediğinde NFC kartı orta konsola dokundurun.",
"Anahtar oluşturulamadı: %1",
"Eşleştirildi.",
"Eşleştirme başarısız: %1",
"Eşleştirme ve anahtarlar",
"Önce VIN'i Ayarlar'da girin. Sonra bir anahtar oluşturun ve BLE ile araçla eşleştirin - onay için aracın yanında durun ve NFC kartı orta konsola dokundurun.",
"Telefon anahtarı başlıyor...",
"Oluşturuluyor...",
"Anahtar oluştur",
"NFC dokunuşu bekleniyor...",
"Aracı eşleştir",
"BLE eşleştirmesi istendi - dokunmatik ekranda / NFC kartta onaylayın.",
"Kayıtlı anahtarlar",
"Kayıtlı anahtarları listele",
"Yapılandırma yükleniyor...",
"Anahtar mevcut",
"Henüz anahtar yok - ana menüde Aracı eşleştir'i kullanın",
"Kaydedildi",
"Kaydetme başarısız: %1",
"Ayarlar",
"Araç VIN'i",
"17 karakterli VIN",
"Ana sayfadaki araç modeli",
"Otomatik, modeli VIN'den seçer",
"Anahtar adı",
"harbour-electric-eel",
"Bağlantı zaman aşımı",
" sn",
"Komut zaman aşımı",
"Kaydet",
"Eşleştirme ve anahtarlar",
"Hakkında",
"Uygulama: ElectricEel %1   |   çekirdek: %2",
"(çok eski / bilinmiyor)",
"Kontrol çekirdeği sürüm bildiremeyecek kadar eski - uygulamayı yeniden yükleyin.",
"Uyumsuzluk: çekirdek %1 - uygulama %2 - uygulamayı yeniden yükleyin.",
"Otomatik (VIN'den)",
"Model 3",
"Model S",
"Model X",
"Model Y",
"Cybertruck",
),
"tt": T(
"Эшләтергә",
" (өстәмә)",
"(билгеләнмәгән)",
"%1 • %2 °C эчтә",
"Климат кабынган",
"Климат сүнгән",
"%1% заряд%2",
" • Зарядлана",
"Ишекләр бикле",
"Ишекләр ачык",
"OK",
"чыгу коды %1",
"%1 эшләтелә...",
"Игътибар",
"Сигнал",
"Фараларны йолдырту",
"Автомобильне уятырга",
"Климат",
"Климатны кабызырга",
"Климатны сүндерергә",
"Температураны көйләргә",
"Утыргычларны җылыту",
"Рульне җылыту",
"Утыргычлар һәм климат автомат",
"Планлы әзерлекне өстәргә",
"Планлы әзерлекне бетерергә",
"Зарядка",
"Зарядканы башларга",
"Зарядканы туктатырга",
"Зарядка портын ачарга",
"Зарядка портын ябарга",
"Зарядка лимитын көйләргә",
"Зарядка тогын көйләргә",
"Зарядканы планлаштырырга",
"Планлы зарядканы гамәлдән чыгарырга",
"Зарядка графигын өстәргә",
"Зарядка графигын бетерергә",
"Йозаклар һәм иминлек",
"Бигеләргә",
"Ачарга",
"Ерактан кабызу (ачкычсыз йөрү)",
"Sentry режимы",
"Valet режимын кабызырга",
"Valet режимын сүндерергә",
"Кунак режимын кабызырга",
"Кунак режимын сүндерергә",
"Кунак мәгълүматларын бетерергә",
"Автосаклау (Model X)",
"Багажниклар һәм тәрәзәләр",
"Арткы багажникны ачарга",
"Арткы багажникны хәрәкәтләндерергә",
"Арткы багажникны ябарга",
"Алгы багажникны ачарга",
"Tonneau ачарга (Cybertruck)",
"Tonneau ябарга (Cybertruck)",
"Tonneau туктатырга (Cybertruck)",
"Тәрәзәләрне җилләтергә",
"Тәрәзәләрне ябарга",
"Медиа",
"Уйнарга / Пауза",
"Киләсе трек",
"Алдагы трек",
"Киләсе яраткан",
"Алдагы яраткан",
"Тавышны арттырырга",
"Тавышны киметергә",
"Тавышны көйләргә",
"Программа",
"Программа яңартуын башларга",
"Программа яңартуын гамәлдән чыгарырга",
"Ачкычлар",
"Теркәлгән ачкычларны күрсәтергә",
"Ачкыч өстәргә",
"Ачкычны бетерергә",
"Сессия турында",
"Диагностика",
"Автомобильне пингларга",
"Автомобиль торышын укырга",
"Кузов идарә блогы торышы",
"Аксессуарлар туклануын сакларга",
"Энергия саклау режимы",
"Идарә үзәге башланмады. Кушымтаны яңадан урнаштырыгыз һәм яңарту өчен аска тартыгыз.",
"Идарә үзәге версияне хәбәр итәр өчен бик иске. Кушымтаны (%1) яңадан урнаштырыгыз һәм яңарту өчен аска тартыгыз.",
"Версияләр туры килми: кушымта %1, үзәк %2. Кушымтаны яңадан урнаштырыгыз һәм яңарту өчен аска тартыгыз.",
"VIN көйләнмәгән",
"Ачкыч әзер",
"Ачкыч юк – Көйләүләр / Бәйләү өчен басыгыз",
" • зарядлана",
"• %1 °C",
"Яңартыла...",
"Торыш билгесез (%1). Автомобиль йоклаган булырга мөмкин – Автомобильне уятырга (Игътибар) сынагыз, аннары Торышны яңартыгыз.",
"Торышны яңарту өчен аска тартыгыз",
"Хәзер яңартылды",
"%1 мин элек яңартылды",
"Категорияләр",
"Максатны җибәрергә",
"Автомобильне бәйләргә",
"Көйләүләр",
"Яңартырга",
"Торышны яңартырга",
"Башта максатны куегыз яки языгыз.",
"Тикшерелә...",
"Җибәрерлек берни юк.",
"Кулланып булмый: %1",
"%1, %2 координатлары — навигация шунда башланачак.",
"„%1“ адресы — автомобиль үзе табачак.",
"Җибәрү уңышсыз: %1",
"Автомобиль навигациясе",
"Максат",
"Адрес, координатлар яки карта сылтамасын куегыз",
"Карап алу",
"Автомобильгә җибәрергә",
"Искәрмәләр",
"Бигеләү/ачу кебек Bluetooth куллана — автомобиль якында булырга тиеш, интернет кирәкми. Координатлар төгәл җибәрелә; адресларны һәм сылтамаларны автомобиль үзе эзли, шуңа күрә гадәти булмаган язылыш телефондагыдан аерылырга мөмкин. Android кушымталарыннан: адресны яки сылтаманы күчереп, өстә куегыз.",
"Ачкыч ясалды. „Автомобильне бәйләргә“ басыгыз һәм автомобиль экраны сорагач NFC-картаны үзәк консольгә терәгез.",
"Ачкыч ясау уңышсыз: %1",
"Бәйләнде.",
"Бәйләү уңышсыз: %1",
"Бәйләү һәм ачкычлар",
"Башта VIN-ны Көйләүләрдә кертегез. Аннары ачкыч ясагыз һәм BLE аша автомобиль белән бәйләгез – раслау өчен автомобиль янында басыгыз һәм NFC-картаны үзәк консольгә терәгез.",
"Телефон ачкычы башлана...",
"Ясала...",
"Ачкыч ясарга",
"NFC тию көтелә...",
"Автомобильне бәйләргә",
"BLE бәйләү соралды – сенсор экранда / NFC-картада раслагыз.",
"Теркәлгән ачкычлар",
"Теркәлгән ачкычларны күрсәтергә",
"Көйләүләр йөкләнә...",
"Ачкыч бар",
"Әлегә ачкыч юк – төп менюда Автомобильне бәйләргә кулланыгыз",
"Сакланды",
"Саклау уңышсыз: %1",
"Көйләүләр",
"Автомобиль VIN-ы",
"17 символлы VIN",
"Баш биттә автомобиль моделе",
"Авто модельне VIN буенча сайлый",
"Ачкыч исеме",
"harbour-electric-eel",
"Тоташу вакыты",
" с",
"Боерык вакыты",
"Сакларга",
"Бәйләү һәм ачкычлар",
"Программа турында",
"Кушымта: ElectricEel %1   |   үзәк: %2",
"(бик иске / билгесез)",
"Идарә үзәге версияне хәбәр итәр өчен бик иске – кушымтаны яңадан урнаштырыгыз.",
"Туры килми: үзәк %1 каршы кушымта %2 – кушымтаны яңадан урнаштырыгыз.",
"Авто (VIN буенча)",
"Model 3",
"Model S",
"Model X",
"Model Y",
"Cybertruck",
),
"et": T(
"Käivita",
" (valikuline)",
"(määramata)",
"%1 • %2 °C sees",
"Kliima sees",
"Kliima väljas",
"%1 % akut%2",
" • Laeb",
"Uksed lukus",
"Uksed lahti",
"OK",
"väljumiskood %1",
"Käivitan %1...",
"Tähelepanu",
"Signaal",
"Tulede vilgutamine",
"Ärata sõiduk",
"Kliima",
"Lülita kliima sisse",
"Lülita kliima välja",
"Sea temperatuur",
"Istmesoojendus",
"Roolisoojendus",
"Istmed ja kliima automaatselt",
"Lisa ajastatud eelkonditsioneerimine",
"Eemalda ajastatud eelkonditsioneerimine",
"Laadimine",
"Alusta laadimist",
"Lõpeta laadimine",
"Ava laadimispesa",
"Sulge laadimispesa",
"Sea laadimispiir",
"Sea laadimisvool",
"Ajakava laadimine",
"Tühista ajastatud laadimine",
"Lisa laadimisgraafik",
"Eemalda laadimisgraafik",
"Lukud ja turvalisus",
"Lukusta",
"Ava",
"Kaugkäivitus (võtmeta sõit)",
"Vahirežiim",
"Valet-režiim sisse",
"Valet-režiim välja",
"Külalisrežiim sisse",
"Külalisrežiim välja",
"Kustuta külalise andmed",
"Automaatkaitse (Model X)",
"Pakiruumid ja aknad",
"Ava tagumine pakiruum",
"Liiguta tagumist pakiruumi",
"Sulge tagumine pakiruum",
"Ava esimene pakiruum",
"Ava tonneau (Cybertruck)",
"Sulge tonneau (Cybertruck)",
"Peata tonneau (Cybertruck)",
"Tuuluta aknaid",
"Sulge aknad",
"Meedia",
"Esita / Paus",
"Järgmine lugu",
"Eelmine lugu",
"Järgmine lemmik",
"Eelmine lemmik",
"Valjemaks",
"Vaiksemaks",
"Sea helitugevus",
"Tarkvara",
"Alusta tarkvarauuendust",
"Tühista tarkvarauuendus",
"Võtmed",
"Loetle registreeritud võtmeid",
"Lisa võti",
"Eemalda võti",
"Seansi info",
"Diagnostika",
"Sõiduki ping",
"Loe sõiduki olekut",
"Kere juhtploki olek",
"Hoia lisaseadmete toide",
"Säästurežiim",
"Juhtimistuum ei käivitunud. Installi rakendus uuesti ja tõmba värskendamiseks alla.",
"Juhtimistuum on liiga vana versiooni teatamiseks. Installi rakendus (%1) uuesti ja tõmba värskendamiseks alla.",
"Versioonikonflikt: rakendus %1, tuum %2. Installi rakendus uuesti ja tõmba värskendamiseks alla.",
"VIN-i pole seadistatud",
"Võti valmis",
"Võtit pole - puuduta Seaded / Sidumine",
" • laeb",
"• %1 °C",
"Värskendan...",
"Olek pole saadaval (%1). Sõiduk võib magada - proovi Ärata sõiduk (Tähelepanu), seejärel Värskenda olekut.",
"Tõmba oleku värskendamiseks alla",
"Värskendatud just",
"Värskendatud %1 min tagasi",
"Kategooriad",
"Saada sihtkoht",
"Seo sõiduk",
"Seaded",
"Värskenda",
"Värskenda olekut",
"Kleebi või kirjuta esmalt sihtkoht.",
"Kontrollin...",
"Pole midagi saata.",
"Ei saa kasutada: %1",
"Koordinaadid %1, %2 — navigeerimine algab seal.",
"Aadress „%1“ — auto otsib selle.",
"Saatmine ebaõnnestus: %1",
"Auto navigatsioon",
"Sihtkoht",
"Kleebi aadress, koordinaadid või kaardilink",
"Eelvaade",
"Saada autosse",
"Märkused",
"Kasutab Bluetoothi nagu lukustamine/avamine — auto peab olema levialas, internetti pole vaja. Koordinaadid saadetakse täpselt; aadressid ja lingid otsib auto ise, seega ebatavaline kirjapilt võib lahenduda teisiti kui telefonis. Androidi rakendustest: kopeeri aadress või link ja kleebi ülal.",
"Võti loodud. Puuduta „Seo sõiduk“ ja hoia NFC-kaarti keskkonsooli vastas, kui auto ekraan küsib.",
"Võtme loomine ebaõnnestus: %1",
"Seotud.",
"Sidumine ebaõnnestus: %1",
"Sidumine ja võtmed",
"Seadista esmalt VIN Seadetes. Seejärel loo võti ja seo see BLE kaudu autoga - seisa sõiduki kõrval ja hoia kinnitamiseks NFC-kaarti keskkonsooli vastas.",
"Telefonivõti käivitub...",
"Loomine...",
"Loo võti",
"Ootan NFC-puudet...",
"Seo sõiduk",
"BLE-sidumine küsitud - kinnita puuteekraanil / NFC-kaardil.",
"Registreeritud võtmed",
"Loetle registreeritud võtmeid",
"Laen konfiguratsiooni...",
"Võti on olemas",
"Võtit veel pole - kasuta Seo sõiduk peamenüüs",
"Salvestatud",
"Salvestamine ebaõnnestus: %1",
"Seaded",
"Sõiduki VIN",
"17-märgiline VIN",
"Automudel esilehel",
"Auto valib mudeli VIN-i järgi",
"Võtme nimi",
"harbour-electric-eel",
"Ühenduse timeout",
" s",
"Käsu timeout",
"Salvesta",
"Sidumine ja võtmed",
"Teave",
"Rakendus: ElectricEel %1   |   tuum: %2",
"(liiga vana / teadmata)",
"Juhtimistuum on liiga vana versiooni teatamiseks - installi rakendus uuesti.",
"Versioonikonflikt: tuum %1 vs rakendus %2 - installi rakendus uuesti.",
"Auto (VIN-i järgi)",
"Model 3",
"Model S",
"Model X",
"Model Y",
"Cybertruck",
),
"vi": T(
"Chạy",
" (tùy chọn)",
"(chưa đặt)",
"%1 • %2 °C bên trong",
"Điều hòa bật",
"Điều hòa tắt",
"%1 % pin%2",
" • Đang sạc",
"Cửa đã khóa",
"Cửa đã mở",
"OK",
"mã thoát %1",
"Đang chạy %1...",
"Chú ý",
"Còi",
"Nháy đèn pha",
"Đánh thức xe",
"Điều hòa",
"Bật điều hòa",
"Tắt điều hòa",
"Đặt nhiệt độ",
"Sưởi ghế",
"Sưởi vô lăng",
"Ghế & điều hòa tự động",
"Thêm điều hòa trước theo lịch",
"Xóa điều hòa trước theo lịch",
"Sạc",
"Bắt đầu sạc",
"Dừng sạc",
"Mở cổng sạc",
"Đóng cổng sạc",
"Đặt giới hạn sạc",
"Đặt dòng sạc",
"Lên lịch sạc",
"Hủy sạc theo lịch",
"Thêm lịch sạc",
"Xóa lịch sạc",
"Khóa & an toàn",
"Khóa",
"Mở khóa",
"Khởi động từ xa (lái không chìa)",
"Chế độ Sentry",
"Bật chế độ valet",
"Tắt chế độ valet",
"Bật chế độ khách",
"Tắt chế độ khách",
"Xóa dữ liệu khách",
"Tự bảo vệ (Model X)",
"Cốp & cửa sổ",
"Mở cốp sau",
"Di chuyển cốp sau",
"Đóng cốp sau",
"Mở cốp trước",
"Mở tonneau (Cybertruck)",
"Đóng tonneau (Cybertruck)",
"Dừng tonneau (Cybertruck)",
"Hé cửa sổ",
"Đóng cửa sổ",
"Media",
"Phát / Tạm dừng",
"Bài tiếp",
"Bài trước",
"Yêu thích tiếp",
"Yêu thích trước",
"Tăng âm lượng",
"Giảm âm lượng",
"Đặt âm lượng",
"Phần mềm",
"Bắt đầu cập nhật phần mềm",
"Hủy cập nhật phần mềm",
"Chìa khóa",
"Liệt kê chìa đã đăng ký",
"Thêm chìa",
"Xóa chìa",
"Thông tin phiên",
"Chẩn đoán",
"Ping xe",
"Đọc trạng thái xe",
"Trạng thái điều khiển thân xe",
"Giữ nguồn phụ kiện",
"Chế độ tiết kiệm",
"Lõi điều khiển không khởi động được. Cài lại ứng dụng rồi kéo xuống để làm mới.",
"Lõi điều khiển quá cũ, không báo được phiên bản. Cài lại ứng dụng (%1) rồi kéo xuống để làm mới.",
"Lệch phiên bản: app %1, lõi %2. Cài lại ứng dụng rồi kéo xuống để làm mới.",
"Chưa cấu hình VIN",
"Chìa sẵn sàng",
"Chưa có chìa - chạm để vào Cài đặt / Ghép nối",
" • đang sạc",
"• %1 °C",
"Đang cập nhật...",
"Không có trạng thái (%1). Xe có thể đang ngủ - thử Đánh thức xe (Chú ý), rồi Làm mới trạng thái.",
"Kéo xuống để làm mới trạng thái",
"Vừa cập nhật",
"Cập nhật %1 phút trước",
"Hạng mục",
"Gửi điểm đến",
"Ghép nối xe",
"Cài đặt",
"Làm mới",
"Làm mới trạng thái",
"Dán hoặc nhập điểm đến trước.",
"Đang kiểm tra...",
"Không có gì để gửi.",
"Không dùng được: %1",
"Tọa độ %1, %2 — dẫn đường sẽ bắt đầu ở đó.",
"Địa chỉ “%1” — xe sẽ tự tìm.",
"Gửi thất bại: %1",
"Dẫn đường xe",
"Điểm đến",
"Dán địa chỉ, tọa độ hoặc link bản đồ",
"Xem trước",
"Gửi tới xe",
"Ghi chú",
"Dùng Bluetooth như khóa/mở khóa — xe phải trong tầm, không cần internet. Tọa độ được gửi chính xác; địa chỉ và link do xe tự tìm, nên cách viết lạ có thể ra khác với trên điện thoại. Từ app Android: chép địa chỉ hoặc link rồi dán ở trên.",
"Đã tạo chìa. Chạm “Ghép nối xe” rồi áp thẻ NFC vào bảng giữa khi màn hình xe yêu cầu.",
"Tạo chìa thất bại: %1",
"Đã ghép nối.",
"Ghép nối thất bại: %1",
"Ghép nối & chìa khóa",
"Đặt VIN trong Cài đặt trước. Rồi tạo chìa và ghép với xe qua BLE - đứng cạnh xe và áp thẻ NFC vào bảng giữa để duyệt.",
"Chìa điện thoại đang khởi động...",
"Đang tạo...",
"Tạo chìa",
"Đang chờ chạm NFC...",
"Ghép nối xe",
"Đã yêu cầu ghép BLE - duyệt trên màn hình / thẻ NFC ngay.",
"Chìa đã đăng ký",
"Liệt kê chìa đã đăng ký",
"Đang tải cấu hình...",
"Đã có chìa",
"Chưa có chìa - dùng Ghép nối xe ở menu chính",
"Đã lưu",
"Lưu thất bại: %1",
"Cài đặt",
"VIN của xe",
"VIN 17 ký tự",
"Mẫu xe trang đầu",
"Tự động chọn mẫu theo VIN",
"Tên chìa",
"harbour-electric-eel",
"Hết giờ kết nối",
" gi",
"Hết giờ lệnh",
"Lưu",
"Ghép nối & chìa khóa",
"Giới thiệu",
"App: ElectricEel %1   |   lõi: %2",
"(quá cũ / không rõ)",
"Lõi điều khiển quá cũ, không báo được phiên bản - cài lại ứng dụng.",
"Lệch: lõi %1 vs app %2 - cài lại ứng dụng.",
"Tự động (theo VIN)",
"Model 3",
"Model S",
"Model X",
"Model Y",
"Cybertruck",
),
}
if __name__ == "__main__":
    write_all(LANGS)
