#!/usr/bin/env python3
"""Batch D: hu ro bg el lt lv. See fill-a.py / fill_common.py."""
import os
import sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from fill_common import write_all


def T(*items):
    return list(items)


LANGS = {
"hu": T(
"Futtatás",
" (nem kötelező)",
"(nincs beállítva)",
"%1 • %2 °C bent",
"Klíma be",
"Klíma ki",
"%1 % akkumulátor%2",
" • Tölt",
"Ajtók zárva",
"Ajtók nyitva",
"OK",
"kilépési kód: %1",
"%1 futtatása...",
"Figyelem",
"Duda",
"Fényszóró-villantás",
"Jármű felébresztése",
"Klíma",
"Klíma bekapcsolása",
"Klíma kikapcsolása",
"Hőmérséklet beállítása",
"Ülésfűtés",
"Kormányfűtés",
"Ülés és klíma automatikusan",
"Előtemperálás ütemezése",
"Előtemperálás törlése",
"Töltés",
"Töltés indítása",
"Töltés leállítása",
"Töltőnyílás nyitása",
"Töltőnyílás zárása",
"Töltési limit beállítása",
"Töltőáram beállítása",
"Töltés ütemezése",
"Ütemezett töltés törlése",
"Töltési ütemterv hozzáadása",
"Töltési ütemterv törlése",
"Zárak és biztonság",
"Zárás",
"Nyitás",
"Távoli indítás (kulcs nélküli vezetés)",
"Őrszem mód",
"Inas mód be",
"Inas mód ki",
"Vendég mód be",
"Vendég mód ki",
"Vendégadatok törlése",
"Automatikus védelem (Model X)",
"Csomagtartók és ablakok",
"Hátsó csomagtartó nyitása",
"Hátsó csomagtartó mozgatása",
"Hátsó csomagtartó zárása",
"Első csomagtartó nyitása",
"Tonneau nyitása (Cybertruck)",
"Tonneau zárása (Cybertruck)",
"Tonneau leállítása (Cybertruck)",
"Ablakok szellőztetése",
"Ablakok zárása",
"Média",
"Lejátszás / Szünet",
"Következő szám",
"Előző szám",
"Következő kedvenc",
"Előző kedvenc",
"Hangerő fel",
"Hangerő le",
"Hangerő beállítása",
"Szoftver",
"Szoftverfrissítés indítása",
"Szoftverfrissítés megszakítása",
"Kulcsok",
"Regisztrált kulcsok listázása",
"Kulcs hozzáadása",
"Kulcs eltávolítása",
"Munkamenet-információ",
"Diagnosztika",
"Jármű pingelése",
"Járműállapot lekérése",
"Karosszériavezérlő állapota",
"Tartozék-tápellátás megtartása",
"Energiatakarékos mód",
"A vezérlőmag nem tudott elindulni. Telepítsd újra az appot, majd húzd lefelé a frissítéshez.",
"A vezérlőmag túl régi a verzió jelentéséhez. Telepítsd újra az appot (%1), majd húzd lefelé a frissítéshez.",
"Verzióeltérés: app %1, mag %2. Telepítsd újra az appot, majd húzd lefelé a frissítéshez.",
"Nincs VIN beállítva",
"Kulcs kész",
"Nincs kulcs – koppints a Beállítások / Párosítás menühöz",
" • tölt",
"• %1 °C",
"Frissítés...",
"Állapot nem érhető el (%1). A jármű valószínűleg alszik – próbáld a Jármű felébresztése (Figyelem), majd az Állapot frissítése.",
"Húzd lefelé az állapot frissítéséhez",
"Épp most frissítve",
"%1 perce frissítve",
"Kategóriák",
"Cél küldése",
"Jármű párosítása",
"Beállítások",
"Frissítés",
"Állapot frissítése",
"Előbb illessz be vagy írj be egy célt.",
"Ellenőrzés...",
"Nincs mit küldeni.",
"Nem használható: %1",
"%1, %2 koordináták — a navigáció ott indul.",
"„%1“ cím – a jármű keresi meg.",
"Küldés sikertelen: %1",
"Autós navigáció",
"Cél",
"Cím, koordináták vagy térképlink beillesztése",
"Előnézet",
"Küldés az autóba",
"Megjegyzések",
"Bluetoothot használ, mint a zárás/nyitás — a járműnek hatótávon belül kell lennie, nincs szükség internetre. A koordináták pontosan mennek; a címeket és linkeket a jármű keresi meg, így a szokatlan írásmód máshogy oldódhat fel, mint a telefonon. Android-alkalmazásokból: másold ki a címet vagy linket, majd illeszd be fent.",
"Kulcs létrehozva. Koppints a „Jármű párosítása“ elemre, majd érintsd az NFC-kártyát a középkonzolhoz, amikor az autó képernyője kéri.",
"Kulcsgenerálás sikertelen: %1",
"Párosítva.",
"Párosítás sikertelen: %1",
"Párosítás és kulcsok",
"Előbb állítsd be a VIN-t a Beállításokban. Aztán hozz létre egy kulcsot és párosítsd BLE-n át a járművel – állj a jármű mellé, és jóváhagyásként érintsd az NFC-kártyát a középkonzolhoz.",
"Telefonkulcs indul...",
"Létrehozás...",
"Kulcs létrehozása",
"Várakozás NFC-érintésre...",
"Jármű párosítása",
"BLE-párosítás kérve – hagyd jóvá az érintőképernyőn / NFC-kártyán.",
"Regisztrált kulcsok",
"Regisztrált kulcsok listázása",
"Konfiguráció betöltése...",
"Kulcs megvan",
"Még nincs kulcs – használd a Jármű párosítása elemet a főmenüben",
"Mentve",
"Mentés sikertelen: %1",
"Beállítások",
"Jármű VIN",
"17 karakteres VIN",
"Autómodell a főoldalon",
"Auto választja a modellt a VIN alapján",
"Kulcs neve",
"harbour-electric-eel",
"Kapcsolódási időtúllépés",
" mp",
"Parancs időtúllépés",
"Mentés",
"Párosítás és kulcsok",
"Névjegy",
"App: ElectricEel %1   |   mag: %2",
"(túl régi / ismeretlen)",
"A vezérlőmag túl régi a verzió jelentéséhez – telepítsd újra az appot.",
"Verzióeltérés: mag %1 vs app %2 – telepítsd újra az appot.",
"Auto (VIN alapján)",
"Model 3",
"Model S",
"Model X",
"Model Y",
"Cybertruck",
),
"ro": T(
"Execută",
" (opțional)",
"(nedefinit)",
"%1 • %2 °C în interior",
"Climatizare pornită",
"Climatizare oprită",
"%1% baterie%2",
" • Se încarcă",
"Uși încuiate",
"Uși descuiate",
"OK",
"cod de ieșire %1",
"Se execută %1...",
"Atenție",
"Claxon",
"Flashuri",
"Trezește vehiculul",
"Climatizare",
"Pornește climatizarea",
"Oprește climatizarea",
"Setează temperatura",
"Încălzire scaune",
"Încălzire volan",
"Scaune și climă automat",
"Programează precondiționarea",
"Șterge precondiționarea programată",
"Încărcare",
"Pornește încărcarea",
"Oprește încărcarea",
"Deschide portul de încărcare",
"Închide portul de încărcare",
"Setează limita de încărcare",
"Setează curentul de încărcare",
"Programează încărcarea",
"Anulează încărcarea programată",
"Adaugă program de încărcare",
"Șterge program de încărcare",
"Încuietori și siguranță",
"Încuie",
"Descuie",
"Pornire de la distanță (condus fără cheie)",
"Mod Santinelă",
"Activează modul valet",
"Dezactivează modul valet",
"Activează modul invitat",
"Dezactivează modul invitat",
"Șterge datele invitatului",
"Autosecurizare (Model X)",
"Portbagaje și geamuri",
"Deschide portbagajul spate",
"Mută portbagajul spate",
"Închide portbagajul spate",
"Deschide portbagajul față",
"Deschide tonneau (Cybertruck)",
"Închide tonneau (Cybertruck)",
"Oprește tonneau (Cybertruck)",
"Aerisește geamurile",
"Închide geamurile",
"Media",
"Redare / Pauză",
"Pista următoare",
"Pista anterioară",
"Favorita următoare",
"Favorita anterioară",
"Volum mai tare",
"Volum mai încet",
"Setează volumul",
"Software",
"Pornește actualizarea software",
"Anulează actualizarea software",
"Chei",
"Listează cheile înregistrate",
"Adaugă cheie",
"Șterge cheie",
"Info sesiune",
"Diagnostic",
"Ping vehicul",
"Citește starea vehiculului",
"Starea unității de caroserie",
"Păstrează alimentarea accesoriilor",
"Mod consum redus",
"Nucleul de control nu a pornit. Reinstalează aplicația și trage în jos pentru actualizare.",
"Nucleul de control este prea vechi pentru a raporta versiunea. Reinstalează aplicația (%1) și trage în jos pentru actualizare.",
"Nepotrivire versiuni: aplicația %1, nucleul %2. Reinstalează aplicația și trage în jos pentru actualizare.",
"Niciun VIN configurat",
"Cheie gata",
"Nicio cheie - atinge pentru Setări / Asociere",
" • se încarcă",
"• %1 °C",
"Se actualizează...",
"Stare indisponibilă (%1). Vehiculul poate dormi - încearcă Trezește vehiculul (Atenție), apoi Actualizează starea.",
"Trage în jos pentru a actualiza starea",
"Actualizat chiar acum",
"Actualizat acum %1 min",
"Categorii",
"Trimite destinația",
"Asociază vehiculul",
"Setări",
"Actualizează",
"Actualizează starea",
"Lipește sau tastează mai întâi o destinație.",
"Se verifică...",
"Nimic de trimis.",
"Nu poate fi folosit: %1",
"Coordonatele %1, %2 — navigarea va începe acolo.",
"Adresa „%1“ — va fi căutată de mașină.",
"Trimitere eșuată: %1",
"Navigația mașinii",
"Destinație",
"Lipește adresă, coordonate sau link hartă",
"Previzualizare",
"Trimite la mașină",
"Note",
"Folosește Bluetooth, ca încuierea/descuierea — mașina trebuie să fie în raza de acțiune, fără internet. Coordonatele se trimit exact; adresele și linkurile sunt căutate de mașină, deci scrierile neobișnuite se pot rezolva diferit față de telefon. Din aplicații Android: copiază adresa sau linkul și lipește mai sus.",
"Cheie generată. Atinge „Asociază vehiculul“, apoi atinge cardul NFC de consola centrală când cere ecranul mașinii.",
"Generarea cheii a eșuat: %1",
"Asociat.",
"Asocierea a eșuat: %1",
"Asociere și chei",
"Setează mai întâi VIN-ul în Setări. Apoi generează o cheie și asociaz-o cu mașina prin BLE - stai lângă vehicul și atinge cardul NFC de consola centrală pentru aprobare.",
"Cheia de telefon pornește...",
"Se generează...",
"Generează cheie",
"Se așteaptă atingerea NFC...",
"Asociază vehiculul",
"Asociere BLE cerută - aprobă pe touchscreen / cardul NFC acum.",
"Chei înregistrate",
"Listează cheile înregistrate",
"Se încarcă configurația...",
"Cheie existentă",
"Încă nicio cheie - folosește Asociază vehiculul din meniul principal",
"Salvat",
"Salvarea a eșuat: %1",
"Setări",
"VIN vehicul",
"VIN de 17 caractere",
"Modelul mașinii pe prima pagină",
"Auto selectează modelul din VIN",
"Numele cheii",
"harbour-electric-eel",
"Timeout conectare",
" s",
"Timeout comandă",
"Salvează",
"Asociere și chei",
"Despre",
"Aplicația: ElectricEel %1   |   nucleu: %2",
"(prea vechi / necunoscut)",
"Nucleul de control este prea vechi pentru a raporta o versiune - reinstalează aplicația.",
"Nepotrivire: nucleu %1 vs aplicația %2 - reinstalează aplicația.",
"Auto (din VIN)",
"Model 3",
"Model S",
"Model X",
"Model Y",
"Cybertruck",
),
"bg": T(
"Изпълни",
" (по избор)",
"(не е зададено)",
"%1 • %2 °C вътре",
"Климатик включен",
"Климатик изключен",
"%1% батерия%2",
" • Зарежда се",
"Врати заключени",
"Врати отключени",
"OK",
"код на изход %1",
"Изпълнява се %1...",
"Внимание",
"Клаксон",
"Мигане с фарове",
"Събуди автомобила",
"Климатик",
"Включи климатик",
"Изключи климатик",
"Задай температура",
"Отопление на седалки",
"Отопление на волан",
"Седалки и климатик автоматично",
"Добави планирано preconditionиране",
"Премахни планирано preconditionиране",
"Зареждане",
"Започни зареждане",
"Спри зареждане",
"Отвори порта за зареждане",
"Затвори порта за зареждане",
"Задай лимит на зареждане",
"Задай ток на зареждане",
"Планирай зареждане",
"Отмени планирано зареждане",
"Добави график за зареждане",
"Премахни график за зареждане",
"Ключалки и сигурност",
"Заключи",
"Отключи",
"Дистанционно стартиране (шофиране без ключ)",
"Режим Sentry",
"Включи режим valet",
"Изключи режим valet",
"Включи режим гост",
"Изключи режим гост",
"Изтрий данните на госта",
"Автозащита (Model X)",
"Багажници и прозорци",
"Отвори задния багажник",
"Премести задния багажник",
"Затвори задния багажник",
"Отвори предния багажник",
"Отвори tonneau (Cybertruck)",
"Затвори tonneau (Cybertruck)",
"Спри tonneau (Cybertruck)",
"Проветри прозорците",
"Затвори прозорците",
"Медия",
"Пусни / Пауза",
"Следващ трак",
"Предишен трак",
"Следващ любим",
"Предишен любим",
"Усили",
"Намали",
"Задай сила на звука",
"Софтуер",
"Започни софтуерна актуализация",
"Отмени софтуерна актуализация",
"Ключове",
"Изброй регистрирани ключове",
"Добави ключ",
"Премахни ключ",
"Информация за сесия",
"Диагностика",
"Ping на автомобила",
"Прочети състоянието на автомобила",
"Състояние на блока за управление на купето",
"Запази захранването на аксесоарите",
"Икономичен режим",
"Контролното ядро не стартира. Преинсталирай приложението и дръпни надолу за обновяване.",
"Контролното ядро е твърде старо, за да съобщи версия. Преинсталирай приложението (%1) и дръпни надолу за обновяване.",
"Несъответствие на версии: приложение %1, ядро %2. Преинсталирай приложението и дръпни надолу за обновяване.",
"Няма конфигуриран VIN",
"Ключът е готов",
"Няма ключ – докосни за Настройки / Сдвояване",
" • зарежда се",
"• %1 °C",
"Обновяване...",
"Състоянието е недостъпно (%1). Автомобилът може да спи – пробвай Събуди автомобила (Внимание), после Обнови състоянието.",
"Дръпни надолу, за да обновиш състоянието",
"Обновено току-що",
"Обновено преди %1 мин",
"Категории",
"Изпрати дестинация",
"Сдвои автомобил",
"Настройки",
"Обнови",
"Обнови състоянието",
"Първо постави или въведи дестинация.",
"Проверка...",
"Няма какво да се изпрати.",
"Не може да се използва: %1",
"Координати %1, %2 — навигацията ще започне там.",
"Адрес „%1“ — колата ще го потърси.",
"Изпращането се провали: %1",
"Навигация на колата",
"Дестинация",
"Постави адрес, координати или връзка към карта",
"Преглед",
"Изпрати на колата",
"Бележки",
"Използва Bluetooth като заключване/отключване — колата трябва да е в обхват, интернет не е нужен. Координатите се изпращат точно; адресите и връзките колата търси сама, затова необичаен правопис може да се разреши различно от телефона. От Android приложения: копирай адреса или връзката и постави по-горе.",
"Ключът е генериран. Докосни „Сдвои автомобил“ и допри NFC картата до централната конзола, когато екранът на колата поиска.",
"Генерирането на ключ се провали: %1",
"Сдвоено.",
"Сдвояването се провали: %1",
"Сдвояване и ключове",
"Първо задай VIN в Настройки. После генерирай ключ и го сдвои с колата през BLE – застани до автомобила и допри NFC картата до централната конзола за одобрение.",
"Телефонният ключ стартира...",
"Генериране...",
"Генерирай ключ",
"Чака се NFC допир...",
"Сдвои автомобил",
"Поискано е BLE сдвояване – одобри на тъчскрийна / NFC картата сега.",
"Регистрирани ключове",
"Изброй регистрирани ключове",
"Зареждане на конфигурация...",
"Ключът съществува",
"Все още няма ключ – използвай Сдвои автомобил от главното меню",
"Запазено",
"Запазването се провали: %1",
"Настройки",
"VIN на автомобила",
"17-символен VIN",
"Модел на колата на първа страница",
"Auto избира модела от VIN",
"Име на ключ",
"harbour-electric-eel",
"Таймаут на връзка",
" s",
"Таймаут на команда",
"Запази",
"Сдвояване и ключове",
"Относно",
"Приложение: ElectricEel %1   |   ядро: %2",
"(твърде старо / неизвестно)",
"Контролното ядро е твърде старо, за да съобщи версия – преинсталирай приложението.",
"Несъответствие: ядро %1 срещу приложение %2 – преинсталирай приложението.",
"Auto (от VIN)",
"Model 3",
"Model S",
"Model X",
"Model Y",
"Cybertruck",
),
"el": T(
"Εκτέλεση",
" (προαιρετικό)",
"(δεν έχει οριστεί)",
"%1 • %2 °C μέσα",
"Κλιματισμός ενεργός",
"Κλιματισμός ανενεργός",
"%1% μπαταρία%2",
" • Φορτίζει",
"Πόρτες κλειδωμένες",
"Πόρτες ξεκλείδωτες",
"OK",
"κωδικός εξόδου %1",
"Εκτέλεση %1...",
"Προσοχή",
"Κόρνα",
"Αναβόσβημα φώτων",
"Αφύπνιση οχήματος",
"Κλιματισμός",
"Ενεργοποίηση κλιματισμού",
"Απενεργοποίηση κλιματισμού",
"Ορισμός θερμοκρασίας",
"Θέρμανση καθισμάτων",
"Θέρμανση τιμονιού",
"Καθίσματα & κλίμα αυτόματα",
"Προσθήκη προγραμματισμένης προθέρμανσης",
"Αφαίρεση προγραμματισμένης προθέρμανσης",
"Φόρτιση",
"Έναρξη φόρτισης",
"Διακοπή φόρτισης",
"Άνοιγμα θύρας φόρτισης",
"Κλείσιμο θύρας φόρτισης",
"Ορισμός ορίου φόρτισης",
"Ορισμός ρεύματος φόρτισης",
"Προγραμματισμός φόρτισης",
"Ακύρωση προγραμματισμένης φόρτισης",
"Προσθήκη προγράμματος φόρτισης",
"Αφαίρεση προγράμματος φόρτισης",
"Κλειδαριές & ασφάλεια",
"Κλείδωμα",
"Ξεκλείδωμα",
"Απομακρυσμένη εκκίνηση (οδήγηση χωρίς κλειδί)",
"Λειτουργία Sentry",
"Ενεργοποίηση λειτουργίας valet",
"Απενεργοποίηση λειτουργίας valet",
"Ενεργοποίηση λειτουργίας επισκέπτη",
"Απενεργοποίηση λειτουργίας επισκέπτη",
"Διαγραφή δεδομένων επισκέπτη",
"Αυτόματη ασφάλιση (Model X)",
"Πορτμπαγκάζ & παράθυρα",
"Άνοιγμα πίσω πορτμπαγκάζ",
"Μετακίνηση πίσω πορτμπαγκάζ",
"Κλείσιμο πίσω πορτμπαγκάζ",
"Άνοιγμα μπροστινού πορτμπαγκάζ",
"Άνοιγμα tonneau (Cybertruck)",
"Κλείσιμο tonneau (Cybertruck)",
"Διακοπή tonneau (Cybertruck)",
"Αερισμός παραθύρων",
"Κλείσιμο παραθύρων",
"Πολυμέσα",
"Αναπαραγωγή / Παύση",
"Επόμενο κομμάτι",
"Προηγούμενο κομμάτι",
"Επόμενο αγαπημένο",
"Προηγούμενο αγαπημένο",
"Αύξηση έντασης",
"Μείωση έντασης",
"Ορισμός έντασης",
"Λογισμικό",
"Έναρξη ενημέρωσης λογισμικού",
"Ακύρωση ενημέρωσης λογισμικού",
"Κλειδιά",
"Λίστα καταχωρημένων κλειδιών",
"Προσθήκη κλειδιού",
"Αφαίρεση κλειδιού",
"Πληροφορίες συνεδρίας",
"Διαγνωστικά",
"Ping οχήματος",
"Ανάγνωση κατάστασης οχήματος",
"Κατάσταση μονάδας αμαξώματος",
"Διατήρηση τροφοδοσίας αξεσουάρ",
"Λειτουργία χαμηλής κατανάλωσης",
"Ο πυρήνας ελέγχου απέτυχε να ξεκινήσει. Επανεγκαταστήστε την εφαρμογή και σύρετε προς τα κάτω για ανανέωση.",
"Ο πυρήνας ελέγχου είναι πολύ παλιός για να αναφέρει έκδοση. Επανεγκαταστήστε την εφαρμογή (%1) και σύρετε προς τα κάτω για ανανέωση.",
"Ασυμφωνία εκδόσεων: εφαρμογή %1, πυρήνας %2. Επανεγκαταστήστε την εφαρμογή και σύρετε προς τα κάτω για ανανέωση.",
"Δεν έχει οριστεί VIN",
"Το κλειδί είναι έτοιμο",
"Χωρίς κλειδί - πατήστε για Ρυθμίσεις / Σύζευξη",
" • φορτίζει",
"• %1 °C",
"Ενημέρωση...",
"Η κατάσταση δεν είναι διαθέσιμη (%1). Το όχημα ίσως κοιμάται - δοκιμάστε Αφύπνιση οχήματος (Προσοχή) και μετά Ανανέωση κατάστασης.",
"Σύρετε προς τα κάτω για ανανέωση κατάστασης",
"Ενημερώθηκε μόλις",
"Ενημερώθηκε πριν %1 λεπ.",
"Κατηγορίες",
"Αποστολή προορισμού",
"Σύζευξη οχήματος",
"Ρυθμίσεις",
"Ανανέωση",
"Ανανέωση κατάστασης",
"Επικολλήστε ή πληκτρολογήστε πρώτα έναν προορισμό.",
"Έλεγχος...",
"Τίποτα για αποστολή.",
"Δεν μπορεί να χρησιμοποιηθεί: %1",
"Συντεταγμένες %1, %2 — η πλοήγηση θα ξεκινήσει εκεί.",
"Διεύθυνση «%1» — θα αναζητηθεί από το αυτοκίνητο.",
"Η αποστολή απέτυχε: %1",
"Πλοήγηση αυτοκινήτου",
"Προορισμός",
"Επικολλήστε διεύθυνση, συντεταγμένες ή σύνδεσμο χάρτη",
"Προεπισκόπηση",
"Αποστολή στο αυτοκίνητο",
"Σημειώσεις",
"Χρησιμοποιεί Bluetooth, όπως το κλείδωμα/ξεκλείδωμα — το αυτοκίνητο πρέπει να είναι εντός εμβέλειας, δεν χρειάζεται internet. Οι συντεταγμένες στέλνονται ακριβώς· διευθύνσεις και σύνδεσμοι αναζητούνται από το ίδιο το αυτοκίνητο, οπότε ασυνήθιστη ορθογραφία μπορεί να επιλυθεί διαφορετικά από ό,τι στο τηλέφωνο. Από εφαρμογές Android: αντιγράψτε τη διεύθυνση ή τον σύνδεσμο και επικολλήστε παραπάνω.",
"Το κλειδί δημιουργήθηκε. Πατήστε «Σύζευξη οχήματος» και ακουμπήστε την κάρτα NFC στην κεντρική κονσόλα όταν το ζητήσει η οθόνη του αυτοκινήτου.",
"Η δημιουργία κλειδιού απέτυχε: %1",
"Συζεύχθηκε.",
"Η σύζευξη απέτυχε: %1",
"Σύζευξη & κλειδιά",
"Ορίστε πρώτα το VIN στις Ρυθμίσεις. Στη συνέχεια δημιουργήστε ένα κλειδί και συζεύξτε το με το αυτοκίνητο μέσω BLE - σταθείτε δίπλα στο όχημα και ακουμπήστε την κάρτα NFC στην κεντρική κονσόλα για έγκριση.",
"Το κλειδί τηλεφώνου εκκινεί...",
"Δημιουργία...",
"Δημιουργία κλειδιού",
"Αναμονή αφής NFC...",
"Σύζευξη οχήματος",
"Ζητήθηκε σύζευξη BLE - εγκρίνετε στην οθόνη αφής / κάρτα NFC τώρα.",
"Καταχωρημένα κλειδιά",
"Λίστα καταχωρημένων κλειδιών",
"Φόρτωση διαμόρφωσης...",
"Το κλειδί υπάρχει",
"Ακόμα χωρίς κλειδί - χρησιμοποιήστε Σύζευξη οχήματος από το κύριο μενού",
"Αποθηκεύτηκε",
"Η αποθήκευση απέτυχε: %1",
"Ρυθμίσεις",
"VIN οχήματος",
"VIN 17 χαρακτήρων",
"Μοντέλο αυτοκινήτου στην αρχική σελίδα",
"Αυτόματη επιλογή μοντέλου από το VIN",
"Όνομα κλειδιού",
"harbour-electric-eel",
"Χρονικό όριο σύνδεσης",
" δ",
"Χρονικό όριο εντολής",
"Αποθήκευση",
"Σύζευξη & κλειδιά",
"Πληροφορίες",
"Εφαρμογή: ElectricEel %1   |   πυρήνας: %2",
"(πολύ παλιός / άγνωστος)",
"Ο πυρήνας ελέγχου είναι πολύ παλιός για να αναφέρει έκδοση - επανεγκαταστήστε την εφαρμογή.",
"Ασυμφωνία: πυρήνας %1 έναντι εφαρμογής %2 - επανεγκαταστήστε την εφαρμογή.",
"Αυτόματο (από VIN)",
"Model 3",
"Model S",
"Model X",
"Model Y",
"Cybertruck",
),
"lt": T(
"Vykdyti",
" (nebūtina)",
"(nenustatyta)",
"%1 • %2 °C viduje",
"Klimatas įjungtas",
"Klimatas išjungtas",
"%1 % baterijos%2",
" • Kraunasi",
"Durys užrakintos",
"Durys atrakintos",
"OK",
"išeities kodas %1",
"Vykdoma %1...",
"Dėmesio",
"Signalas",
"Mirksėjimas žibintais",
"Pažadinti transporto priemonę",
"Klimatas",
"Įjungti klimatą",
"Išjungti klimatą",
"Nustatyti temperatūrą",
"Sėdynių šildymas",
"Vairo šildymas",
"Sėdynės ir klimatas automatiškai",
"Pridėti planuotą išankstinį paruošimą",
"Pašalinti planuotą išankstinį paruošimą",
"Įkrovimas",
"Pradėti įkrovimą",
"Stabdyti įkrovimą",
"Atidaryti įkrovimo lizdą",
"Uždaryti įkrovimo lizdą",
"Nustatyti įkrovimo ribą",
"Nustatyti įkrovimo srovę",
"Suplanuoti įkrovimą",
"Atšaukti planuotą įkrovimą",
"Pridėti įkrovimo tvarkaraštį",
"Pašalinti įkrovimo tvarkaraštį",
"Užraktai ir sauga",
"Užrakinti",
"Atrakinti",
"Nuotolinis paleidimas (važiavimas be rakto)",
"Sentry režimas",
"Įjungti valet režimą",
"Išjungti valet režimą",
"Įjungti svečio režimą",
"Išjungti svečio režimą",
"Ištrinti svečio duomenis",
"Automatinė apsauga (Model X)",
"Bagažinės ir langai",
"Atidaryti galinę bagažinę",
"Judinti galinę bagažinę",
"Uždaryti galinę bagažinę",
"Atidaryti priekinę bagažinę",
"Atidaryti tonneau (Cybertruck)",
"Uždaryti tonneau (Cybertruck)",
"Stabdyti tonneau (Cybertruck)",
"Vėdinti langus",
"Uždaryti langus",
"Medija",
"Leisti / Pauzė",
"Kitas takelis",
"Ankstesnis takelis",
"Kitas mėgstamiausias",
"Ankstesnis mėgstamiausias",
"Garsiau",
"Tyliau",
"Nustatyti garsumą",
"Programinė įranga",
"Pradėti programinės įrangos atnaujinimą",
"Atšaukti programinės įrangos atnaujinimą",
"Raktai",
"Išvardyti registruotus raktus",
"Pridėti raktą",
"Pašalinti raktą",
"Seanso informacija",
"Diagnostika",
"Transporto priemonės ping",
"Gauti transporto priemonės būseną",
"Kėbulo valdiklio būsena",
"Palikti priedų maitinimą",
"Energijos taupymo režimas",
"Valdymo branduolys nepaleistas. Iš naujo įdiekite programą ir braukite žemyn, kad atnaujintumėte.",
"Valdymo branduolys per senas versijai pranešti. Iš naujo įdiekite programą (%1) ir braukite žemyn, kad atnaujintumėte.",
"Versijų neatitiktis: programa %1, branduolys %2. Iš naujo įdiekite programą ir braukite žemyn, kad atnaujintumėte.",
"VIN nenustatytas",
"Raktas paruoštas",
"Nėra rakto – bakstelėkite Nustatymai / Susiejimas",
" • kraunasi",
"• %1 °C",
"Atnaujinama...",
"Būsena nepasiekiama (%1). Transporto priemonė gali miegoti – bandykite Pažadinti transporto priemonę (Dėmesio), tada Atnaujinti būseną.",
"Braukite žemyn, kad atnaujintumėte būseną",
"Atnaujinta ką tik",
"Atnaujinta prieš %1 min",
"Kategorijos",
"Siųsti paskirties vietą",
"Susieti transporto priemonę",
"Nustatymai",
"Atnaujinti",
"Atnaujinti būseną",
"Pirmiausia įklijuokite arba įveskite paskirties vietą.",
"Tikrinama...",
"Nėra ką siųsti.",
"Negalima naudoti: %1",
"Koordinatės %1, %2 — navigacija prasidės ten.",
"Adresas „%1“ — automobilis jį suras.",
"Siųsti nepavyko: %1",
"Automobilio navigacija",
"Paskirties vieta",
"Įklijuokite adresą, koordinates arba žemėlapio nuorodą",
"Peržiūra",
"Siųsti į automobilį",
"Pastabos",
"Naudojamas Bluetooth, kaip užrakinant/atrakinant — automobilis turi būti pasiekiamas, interneto nereikia. Koordinatės siunčiamos tiksliai; adresus ir nuorodas automobilis suranda pats, todėl neįprasta rašyba gali būti suprasta kitaip nei telefone. Iš Android programų: nukopijuokite adresą ar nuorodą ir įklijuokite aukščiau.",
"Raktas sugeneruotas. Bakstelėkite „Susieti transporto priemonę“ ir priglauskite NFC kortelę prie centrinės konsolės, kai paprašys automobilio ekranas.",
"Nepavyko sugeneruoti rakto: %1",
"Susieta.",
"Susieti nepavyko: %1",
"Susiejimas ir raktai",
"Pirmiausia nustatykite VIN skiltyje Nustatymai. Tada sugeneruokite raktą ir susiekite jį su automobiliu per BLE – stovėkite prie transporto priemonės ir patvirtindami priglauskite NFC kortelę prie centrinės konsolės.",
"Telefono raktas paleidžiamas...",
"Generuojama...",
"Generuoti raktą",
"Laukiama NFC prisilietimo...",
"Susieti transporto priemonę",
"Paprašyta BLE susiejimo – patvirtinkite jutikliniame ekrane / NFC kortelėje dabar.",
"Registruoti raktai",
"Išvardyti registruotus raktus",
"Įkeliama konfigūracija...",
"Raktas yra",
"Kol kas rakto nėra – naudokite Susieti transporto priemonę pagrindiniame meniu",
"Išsaugota",
"Išsaugoti nepavyko: %1",
"Nustatymai",
"Transporto priemonės VIN",
"17 simbolių VIN",
"Automobilio modelis pradžios puslapyje",
"Auto parenka modelį pagal VIN",
"Rakto pavadinimas",
"harbour-electric-eel",
"Prisijungimo skirtoji trukmė",
" s",
"Komandos skirtoji trukmė",
"Išsaugoti",
"Susiejimas ir raktai",
"Apie",
"Programa: ElectricEel %1   |   branduolys: %2",
"(per senas / nežinomas)",
"Valdymo branduolys per senas versijai pranešti – iš naujo įdiekite programą.",
"Versijų neatitiktis: branduolys %1 ir programa %2 – iš naujo įdiekite programą.",
"Auto (pagal VIN)",
"Model 3",
"Model S",
"Model X",
"Model Y",
"Cybertruck",
),
"lv": T(
"Izpildīt",
" (neobligāti)",
"(nav iestatīts)",
"%1 • %2 °C iekšā",
"Klimats ieslēgts",
"Klimats izslēgts",
"%1 % akumulatora%2",
" • Uzlādējas",
"Durvis aizslēgtas",
"Durvis atslēgtas",
"OK",
"izejas kods %1",
"Izpilda %1...",
"Uzmanību",
"Signāls",
"Mirgošana ar lukturiem",
"Pamodināt transportlīdzekli",
"Klimats",
"Ieslēgt klimatu",
"Izslēgt klimatu",
"Iestatīt temperatūru",
"Sēdekļu apsilde",
"Stūres apsilde",
"Sēdekļi un klimats automātiski",
"Pievienot plānoto priekšsildīšanu",
"Noņemt plānoto priekšsildīšanu",
"Uzlāde",
"Sākt uzlādi",
"Apturēt uzlādi",
"Atvērt uzlādes pieslēgumu",
"Aizvērt uzlādes pieslēgumu",
"Iestatīt uzlādes limitu",
"Iestatīt uzlādes strāvu",
"Ieplānot uzlādi",
"Atcelt ieplānoto uzlādi",
"Pievienot uzlādes grafiku",
"Noņemt uzlādes grafiku",
"Slēdzenes un drošība",
"Aizslēgt",
"Atslēgt",
"Tālvadības starts (braukšana bez atslēgas)",
"Sentry režīms",
"Ieslēgt valet režīmu",
"Izslēgt valet režīmu",
"Ieslēgt viesa režīmu",
"Izslēgt viesa režīmu",
"Dzēst viesa datus",
"Automātiskā aizsardzība (Model X)",
"Bagāžnieki un logi",
"Atvērt aizmugurējo bagāžnieku",
"Kustināt aizmugurējo bagāžnieku",
"Aizvērt aizmugurējo bagāžnieku",
"Atvērt priekšējo bagāžnieku",
"Atvērt tonneau (Cybertruck)",
"Aizvērt tonneau (Cybertruck)",
"Apturēt tonneau (Cybertruck)",
"Vēdināt logus",
"Aizvērt logus",
"Mediji",
"Atskaņot / Pauze",
"Nākamais ieraksts",
"Iepriekšējais ieraksts",
"Nākamais favorīts",
"Iepriekšējais favorīts",
"Skaļāk",
"Klusāk",
"Iestatīt skaļumu",
"Programmatūra",
"Sākt programmatūras atjauninājumu",
"Atcelt programmatūras atjauninājumu",
"Atslēgas",
"Uzskaitīt reģistrētās atslēgas",
"Pievienot atslēgu",
"Noņemt atslēgu",
"Sesijas informācija",
"Diagnostika",
"Transportlīdzekļa ping",
"Nolasīt transportlīdzekļa statusu",
"Virsbūves vadības bloka statuss",
"Saglabāt piederumu barošanu",
"Enerģijas taupīšanas režīms",
"Vadības kodols neizdevās startēt. Pārinstalējiet lietotni un velciet uz leju, lai atjauninātu.",
"Vadības kodols ir pārāk vecs, lai ziņotu versiju. Pārinstalējiet lietotni (%1) un velciet uz leju, lai atjauninātu.",
"Versiju neatbilstība: lietotne %1, kodols %2. Pārinstalējiet lietotni un velciet uz leju, lai atjauninātu.",
"VIN nav konfigurēts",
"Atslēga gatava",
"Nav atslēgas – pieskarieties Iestatījumi / Savienošana",
" • uzlādējas",
"• %1 °C",
"Atjaunina...",
"Statuss nav pieejams (%1). Transportlīdzeklis varbūt guļ – mēģiniet Pamodināt transportlīdzekli (Uzmanību), tad Atjaunināt statusu.",
"Velciet uz leju, lai atjauninātu statusu",
"Atjaunināts tikko",
"Atjaunināts pirms %1 min",
"Kategorijas",
"Sūtīt galamērķi",
"Savienot transportlīdzekli",
"Iestatījumi",
"Atjaunināt",
"Atjaunināt statusu",
"Vispirms ielīmējiet vai ierakstiet galamērķi.",
"Pārbauda...",
"Nekā sūtāma.",
"Nevar izmantot: %1",
"Koordinātas %1, %2 — navigācija sāksies tur.",
"Adrese „%1“ — automašīna to uzmeklēs.",
"Sūtīšana neizdevās: %1",
"Automašīnas navigācija",
"Galamērķis",
"Ielīmējiet adresi, koordinātas vai kartes saiti",
"Priekšskatījums",
"Sūtīt uz automašīnu",
"Piezīmes",
"Izmanto Bluetooth kā aizslēgšana/atslēgšana — automašīnai jābūt sasniedzamā, internets nav vajadzīgs. Koordinātas tiek sūtītas precīzi; adreses un saites automašīna uzmeklē pati, tāpēc neparasta rakstība var tikt saprasta citādi nekā telefonā. No Android lietotnēm: nokopējiet adresi vai saiti un ielīmējiet augšā.",
"Atslēga izveidota. Pieskarieties “Savienot transportlīdzekli” un pielieciet NFC karti pie viduskonsoles, kad to prasa automašīnas ekrāns.",
"Atslēgas izveide neizdevās: %1",
"Savienots.",
"Savienošana neizdevās: %1",
"Savienošana un atslēgas",
"Vispirms iestatiet VIN sadaļā Iestatījumi. Pēc tam izveidojiet atslēgu un savienojiet to ar automašīnu, izmantojot BLE – stāviet pie transportlīdzekļa un apstiprināšanai pielieciet NFC karti pie viduskonsoles.",
"Tālruņa atslēga startē...",
"Izveido...",
"Izveidot atslēgu",
"Gaida NFC pieskārienu...",
"Savienot transportlīdzekli",
"Pieprasīta BLE savienošana – apstipriniet skārienekrānā / NFC kartē tūlīt.",
"Reģistrētās atslēgas",
"Uzskaitīt reģistrētās atslēgas",
"Ielādē konfigurāciju...",
"Atslēga ir",
"Pagaidām nav atslēgas – izmantojiet Savienot transportlīdzekli galvenajā izvēlnē",
"Saglabāts",
"Saglabāšana neizdevās: %1",
"Iestatījumi",
"Transportlīdzekļa VIN",
"17 rakstzīmju VIN",
"Automašīnas modelis sākumlapā",
"Auto izvēlas modeli pēc VIN",
"Atslēgas nosaukums",
"harbour-electric-eel",
"Savienojuma noildze",
" s",
"Komandas noildze",
"Saglabāt",
"Savienošana un atslēgas",
"Par",
"Lietotne: ElectricEel %1   |   kodols: %2",
"(pārāk vecs / nezināms)",
"Vadības kodols ir pārāk vecs, lai ziņotu versiju – pārinstalējiet lietotni.",
"Versiju neatbilstība: kodols %1 pret lietotni %2 – pārinstalējiet lietotni.",
"Auto (pēc VIN)",
"Model 3",
"Model S",
"Model X",
"Model Y",
"Cybertruck",
),
}
if __name__ == "__main__":
    write_all(LANGS)
